using Retrograde;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Retrograde.AI.Utils
{
    public class FlavourSeedData
    {
        public static string AddFlavourToTargetBook(string BookPrompt)
        {
            //Flavours that add variation between generations
            List<string> PromptOptions = new List<string>
            {
                "Include hints of romantic tension—unspoken crushes, forbidden relationships, jealousy, or awkward encounters.",
                "Include a moment where they recognize that healing sometimes feels like numbness, and wonder if that's progress or simply survival.",
                "Include a moment where they admit they can no longer tell who they can trust, convinced someone close is plotting against them.",
                "Have them describe hearing whispers or movements they can't explain, certain someone is watching from the shadows.",
                "Include a reflection on documents or messages they found that don't add up, leading them to suspect a hidden conspiracy.",
                "Have them express fear that their communications are being intercepted, forcing them to write cautiously or cryptically.",
                "Include a moment where they second-guess an ally's kindness, wondering if it's genuine or a calculated trap.",
                "Have them obsess over patterns—footsteps, schedules, odd glances—convinced these small signs reveal a threat.",
                "Include a mention of sleepless nights where every creak or rustle feels like someone approaching them.",
                "Have them question whether their enemies are already within their circle, hiding behind familiar faces while plotting.",
                "Include a fleeting thought that even their own memories might be altered or unreliable, leaving them unsure what is real.",
                "Have them describe the growing certainty that someone is always one step ahead of them, anticipating their every move.",
                "Have them confess that their personal relationships are falling apart faster than they can hold them together.",
                "Have them justify their actions as necessary, insisting no one else had the courage to do what they did.",
                "Include a moment where they argue that the world forced their hand, leaving them no choice but to act as they have.",
                "Have them claim that everyone judging them would have done the same in their situation—if they were honest.",
                "Include a reflection where they paint themselves as a misunderstood hero rather than a villain.",
                "Have them insist that their so-called crimes were actually acts of survival, not malice.",
                "Include a moment where they blame others for pushing them to extremes, absolving themselves of responsibility.",
                "Have them argue that their victims were complicit in their own downfall, one way or another.",
                "Include a justification that rules and laws are tools of the weak, and they refuse to be limited by them.",
                "Have them reframe their betrayals as strategic necessities rather than moral failings.",
                "Include a moment where they claim the ends always justify the means—especially when they are the one deciding the ends.",
                "Have them insist that anyone who opposes them simply doesn't understand their brilliance or vision.",
                "Include a reflection where they portray themselves as the only one capable of making the hard decisions.",
                "Have them accuse others of hypocrisy, claiming they're merely more honest about doing what needs to be done.",
                "Include a moment where they rewrite past events to cast themselves as the victim of unfair judgment.",
                "Have them justify cruelty as discipline, claiming it forges stronger people around them.",
                "Include a moment where they argue that mercy would have caused more harm than their harsh choices.",
                "Have them claim that fate or destiny chose them, and therefore their actions are beyond ordinary morality.",
                "Include a justification that power naturally belongs to those willing to seize it.",
                "Have them insist that their enemies brought their fate upon themselves by standing in the way.",
                "Include a reflection where they convince themselves that those they hurt were obstacles, not people.",
                "Have them reinterpret betrayal as liberation—freeing others from their own misguided paths.",
                "Include a moment where they claim that if they hadn't acted, someone worse would have.",
                "Have them assert that their intelligence places them above conventional ethical constraints.",
                "Include a justification that loyalty is overrated, and only results truly matter.",
                "Have them insist that anyone calling them dangerous simply fears what they don't understand.",
                "Include a moment where they frame manipulation as guidance, claiming others needed their direction.",
                "Have them argue that their selfishness is actually a form of clarity others lack.",
                "Include a reflection where they celebrate their ruthlessness as a virtue in a broken world.",
                "Have them claim that regret is pointless because every choice they made was the correct one.",
                "Include a moment where they confidently declare that history will vindicate them, even if no one else will.",
                "Have them describe how their morals have slowly eroded, and how disturbingly easy it has become to cross new lines.",
                "Include a moment where they feel a thrill from doing something they once believed was wrong, recognizing how far they've fallen.",
                "Have them admit that harming others no longer bothers them the way it used to, and wonder when that shift happened.",
                "Include a reflection where they take pride in manipulation or cruelty, seeing it as a sign of strength rather than decay.",
                "Have them justify exploiting the vulnerable, claiming that weakness exists to be used.",
                "Include a moment where they recognize the person they used to be—and feel nothing but contempt for that version of themselves.",
                "Have them describe ignoring their conscience so many times that it eventually stopped speaking to them.",
                "Include a reflection where they acknowledge they now measure right and wrong by convenience rather than principle.",
                "Have them recount a moment when they enjoyed watching someone suffer, realizing they no longer pretend to care.",
                "Include a moment where they see someone else's morality as naive and mock them for it, openly or internally.",
                "Have them admit they've grown addicted to power, control, or fear, and feel hollow without it.",
                "Include a description of how they've started treating people as tools or obstacles rather than human beings.",
                "Have them realize they crossed a moral line long ago—and now keep running just to avoid facing it.",
                "Include a moment where they twist morality into a weapon, using it only when it benefits them.",
                "Have them confess that corruption was not a fall, but a choice they embraced willingly.",
                "Include a reflection where they measure their worth by how effectively they can break or bend others.",
                "Have them describe how guilt has faded into numbness, leaving them free to act without hesitation.",
                "Include a moment where they look at an innocent person and feel nothing but opportunity.",
                "Have them acknowledge that they now fear redemption—not because it seems impossible, but because they no longer want it.",
                "Include a moment where they catch themselves savoring the thought of crossing an even darker line next.",
                "Have them describe a moment where they inflicted pain simply to see how someone would react, and felt a cold satisfaction.",
                "Include a reflection where they admit they've grown curious about how far they can push someone before they break.",
                "Have them recount a time they watched someone suffer and chose not to intervene, savoring the power it gave them.",
                "Include a moment where they justify their cruelty as a lesson others needed to learn.",
                "Have them describe enjoying the fear in someone's eyes, recognizing it as proof of their control.",
                "Include a reflection where they admit hurting others has become easier—almost routine.",
                "Have them recall a moment when someone begged for mercy, and how denying it made them feel powerful.",
                "Include a moment where they test how much cruelty they can disguise as necessity.",
                "Have them describe harming someone not out of anger or strategy, but pure curiosity.",
                "Include a reflection where they acknowledge they could have been kind, and deliberately chose not to be.",
                "Have them recount a situation where they exploited someone's vulnerability with calculated precision.",
                "Include a moment where they mock someone's pain, seeing it as weakness rather than something to empathize with.",
                "Have them describe taking pleasure in ruining someone's hopes or plans, just to watch their reaction.",
                "Include a reflection where they recognize that others fear them—and secretly enjoy that fear.",
                "Have them recount deliberately manipulating someone into harming themselves emotionally or physically.",
                "Include a moment where they admit cruelty has become a habit, something they perform without thinking.",
                "Have them describe feeling bored when people obey, craving the challenge of breaking those who resist.",
                "Include a reflection where they enjoy withholding something—information, help, comfort—just to watch someone struggle.",
                "Have them recount a moment where they escalated conflict intentionally, savoring the chaos it caused.",
                "Include a moment where they acknowledge that kindness feels foreign now, replaced entirely by sharp, predatory instincts.",
                "Have them cite philosophical ideas to justify their actions, convincing themselves that morality is subjective anyway.",
                "Include a moment where they claim that human behavior is driven by instinct, freeing themselves from responsibility.",
                "Have them reflect on the idea that suffering builds character, using it to excuse what they've done to others.",
                "Include a justification that people create their own misery, and they merely accelerate the inevitable.",
                "Have them use psychological theories to explain away their cruelty as a natural coping mechanism.",
                "Include a moment where they reinterpret their selfishness as healthy self-preservation, grounded in 'rational' thinking.",
                "Have them claim that empathy is a social construct and that freeing themselves from it brings clarity.",
                "Include a reflection where they argue that purpose and meaning are illusions, making any action permissible.",
                "Have them twist philosophical teachings into excuses for manipulation or betrayal.",
                "Include a moment where they insist that everyone is ruled by unconscious impulses, so blaming themselves is pointless.",
                "Have them justify their actions through a belief in determinism, insisting they had no real choice anyway.",
                "Include a reflection where they adopt a nihilistic worldview to distance themselves from guilt or consequences.",
                "Have them use armchair psychology to diagnose others' flaws, avoiding scrutiny of their own behavior.",
                "Include a moment where they claim that morality evolves, and they're simply ahead of everyone else ethically.",
                "Have them convince themselves they are conducting 'experiments' on human nature rather than harming people.",
                "Include a reflection where they argue that emotional detachment is a sign of enlightenment rather than decay.",
                "Have them justify manipulation as a form of guiding others toward their 'true potential.'",
                "Include a moment where they use philosophical paradoxes to muddy their own sense of right and wrong.",
                "Have them claim that guilt is merely a conditioned response, one they have successfully outgrown.",
                "Include a reflection where they reframe their darkest impulses as authenticity—being true to their 'real self.'",
                "Include a moment where they realize they've pushed someone important away without meaning to, and now regret it deeply.",
                "Have them describe how constant stress is making them lash out at people they care about, even when they don't want to.",
                "Include a reflection on how their old routines, comforts, or joys no longer feel like they belong to them.",
                "Have them admit they no longer recognize the person they're becoming, and fear it's too late to turn back.",
                "Include a moment where they try to contact someone they love, only to realize they have no idea what to say anymore.",
                "Have them describe the painful moment they understood a relationship they valued has quietly died over time.",
                "Include a realization that their work, choices, or obsessions have consumed everything else in their life.",
                "Have them hide their guilt behind lofty quotes or theories, hoping complex words will distract from simple wrongdoing.",
                "Include a moment where they speak in grand academic tones to make their actions sound profound rather than cruel.",
                "Have them overanalyze trivial details to appear intelligent, avoiding the emotional truth beneath their behavior.",
                "Include a reflection where they bury remorse under layers of abstract reasoning, pretending depth where none exists.",
                "Have them use obscure terminology to make others doubt whether they even understand the situation well enough to blame them.",
                "Include a moment where they frame their harmful choices as part of a 'greater intellectual framework,' masking their insecurity.",
                "Have them pretend to be above ordinary morality by referencing philosophers they barely understand.",
                "Include a reflection where they nitpick semantics to avoid admitting fault, turning guilt into a debate instead of a confession.",
                "Have them insist that only the 'enlightened' can comprehend their motives, using pretension to dodge accountability.",
                "Include a moment where they drown their conscience in pedantic arguments, hoping complexity will smother the truth.",
                "Have them confess they've been hiding their struggles from everyone, terrified that vulnerability will break what little they have left.",
                "Include a moment where they reflect on how loneliness crept in slowly, until it became the only constant in their life.",
                "Have them reminisce about the simple routines they once had—morning habits, favorite foods, or quiet hobbies.",
                "Include a moment where they recall a job they used to do, unremarkable but steady, and how different life felt then.",
                "Have them describe a familiar street, shop, or café they visited regularly before everything changed.",
                "Include a reflection on an old friend or coworker they lost touch with long before turning to crime.",
                "Have them recall the mundane frustrations of their old life—long lines, broken appliances, nosy neighbors.",
                "Include a moment where they remember saving up for small purchases, appreciating every coin.",
                "Have them describe a favorite place they used to relax, simple and ordinary, now impossibly distant.",
                "Include a memory of chores or tasks they used to complain about, now seeming strangely comforting in hindsight.",
                "Have them recall a hobby they once practiced—gardening, tinkering, reading—that grounded them.",
                "Include a moment where they reflect on old clothes, tools, or belongings they left behind without meaning to.",
                "Have them describe a daily commute they once found boring, now almost nostalgic in its predictability.",
                "Include a memory of cooking simple meals or sharing them with someone before their life unraveled.",
                "Have them recall an ordinary responsibility they had—taking care of a pet, paying bills, fixing leaks.",
                "Include a moment where they remember casual conversations with neighbors or acquaintances they barely knew.",
                "Have them describe the feeling of coming home after a long day, something they took for granted then.",
                "Include a memory of small celebrations—birthdays, local festivals, or quiet gatherings—before trouble began.",
                "Have them reflect on a familiar sound from their old life—traffic, music, a kettle—now tied to bittersweet nostalgia.",
                "Include a moment where they think about a mundane goal they once had, like redecorating a room or learning a skill.",
                "Have them recall the unexpected comfort of predictable routines they never expected to miss.",
                "Include a reflection on how their old, uneventful life now feels like someone else's story entirely.",
                "Have them recall a time when they believed people were fundamentally good, and how that belief quietly died.",
                "Include a moment where they reflect on their younger self with disbelief, wondering how they ever felt so hopeful.",
                "Have them remember an early moment when they first realized the world was harsher than they'd been taught.",
                "Include a reflection on a childhood belief or dream they once cherished, now feeling impossibly naïve.",
                "Have them describe the specific event that shattered their sense of safety or trust for the first time.",
                "Include a moment where they admit they used to see the world in simple terms—right and wrong—before everything got complicated.",
                "Have them recall a time when they trusted someone completely, only to be betrayed in a way they never forgot.",
                "Include a reflection on how their empathy has faded, tracing the slow erosion back to its earliest cracks.",
                "Have them describe the moment they realized the adults they admired were flawed, frightened, or corrupt.",
                "Include a memory of a place that once felt magical or comforting, now colored by bitterness or loss.",
                "Have them recall a promise they once made to themselves—one they broke long ago without noticing.",
                "Include a moment where they remember believing consequences were fair, before learning how arbitrary life can be.",
                "Have them reflect on a childhood fear that now seems trivial compared to the dangers they've survived.",
                "Include a memory of someone who tried to protect their innocence, and how they failed—or how the world overpowered them.",
                "Have them describe realizing that kindness could be exploited, and how that changed them forever.",
                "Include a moment where they face something they once found shocking but now accept with disturbing ease.",
                "Have them recall the first time they lied, stole, or harmed someone, and how strangely momentous it felt.",
                "Include a reflection on how their values shifted over time, slipping further from what they once believed was right.",
                "Have them acknowledge they can no longer remember the last moment they felt truly innocent.",
                "Include a moment where they question whether that innocence was ever real—or just a story they told themselves."
            };
            Random random = RandomProvider.Random;

            int count = 1 + random.Next(5);

            var selected = PromptOptions
                .OrderBy(x => random.Next())
                .Take(count);

            foreach (var prompt in selected)
            {
                BookPrompt += prompt + " ";
            }

            return BookPrompt;
        }

        public static string GetQuestTheme()
        {
            Random random = RandomProvider.Random;
            List<string> questThemes = new List<string>()
            {
                "Corporate espionage thriller",
                "Frontier survival adventure",
                "Political conspiracy drama",
                "Underworld crime investigation",
                "Space-pirate hunting action",
                "High-tech infiltration stealth mission",
                "Frontier law enforcement procedural",
                "Scientific mystery exploration",
                "Interstellar noir detective case",
                "Post-war tension diplomacy scenario",
                "Cyberpunk corporate intrigue",
                "Cult infiltration psychological drama",
                "Resource-rush frontier scramble",
                "Black-market smuggling caper",
                "Megacorp sabotage operation",
                "Deep-space horror encounter",
                "Military rogue-unit pursuit",
                "Neon nightlife criminal underbelly story",
                "Lost-colony recovery expedition",
                "Derelict starship salvage thriller",
                "High-stakes data heist operation",
                "Freestar ranger borderlands pursuit",
                "UC black-ops containment mission",
                "Ancient alien artifact investigation",
                "Corporate whistleblower extraction",
                "Frontier homestead defense scenario",
                "Deep-cover pirate masquerade mission",
                "Smuggler network dismantling operation",
                "Grav-drive experimental test gone wrong",
                "Rogue AI containment emergency",
                "Volatile research site lockdown",
                "House Va'ruun zealot interception",
                "Trade Authority corruption scandal",
                "Undercover mercenary infiltration",
                "Disaster response and evacuation effort",
                "Outlaw biker-gang turf conflict (space variant)",
                "Terrormorph outbreak suppression",
                "Biohazard quarantine breach investigation",
                "Solar flare survival challenge",
                "Xenobiology specimen recovery mission",
                "Inter-corporate hostage negotiation",
                "Crimson Fleet double-cross mystery",
                "Long-range survey mission sabotage",
                "Contraband ring intelligence sweep",
                "Ancient ruins deep-dive expedition",
                "Corporate prototype theft recovery",
                "Weapons-testing black-site investigation",
                "Espionage sting in a luxury resort",
                "Orbital mining strike conflict",
                "Colony disappearance follow-up inquiry",
                "Mech parts smuggling crackdown",
                "Crew mutiny resolution scenario",
                "Ranger-led wilderness tracking operation",
                "Political prisoner rescue mission",
                "Secret military archive decryption quest",
                "Underbelly gang uprising response",
                "Off-grid commune infiltration",
                "Terraforming experiment failure investigation",
                "Illegal robotics production bust",
                "High-risk courier delivery under pursuit",
                "Medical crisis response on a remote outpost",
                "Corporate buyout sabotage drama",
                "Starship ghost-signal investigation",
                "False-flag operation exposure",
                "Undercover assignment in a hostile faction",
                "Freestar–UC cold war brinksmanship story",
                "Cybernetic augmentation trafficking probe",
                "Space station meltdown containment mission",
                "Unethical bio-experimentation operation",
                "Terrormorph gene-splicing conspiracy",
                "Illegal AI sentience creation program",
                "Organ harvesting black-site operation",
                "Mind-control neuroamp enhancement ring",
                "Forced labor exploitation network",
                "Corporate assassination contractor scheme",
                "Population surveillance and data theft project",
                "Weaponized xenofauna breeding initiative",
                "Grav-drive destabilization sabotage plot",
                "Forbidden cult indoctrination experiment",
                "Planetary resource theft and ecological ruin plot",
                "Starship hijacking and identity erasure program",
                "Dark-market cybernetic implantation racket",
                "Smuggled children indoctrination pipeline",
                "Atmospheric poisoning terraforming scam",
                "False-flag attack manufacturing project",
                "Memory-wiping psychological torture facility",
                "Space station plague-release plan",
                "Extinction-level prototype weapons testing scheme",
                "Fanatical ritual sacrifice operation",
                "Mind-breaking indoctrination compound",
                "Forbidden prophecy fulfillment scheme",
                "Brainwashing sermon-frequency experiment",
                "Cult-run abductee conversion program",
                "Star-serpent omens manipulation plot",
                "Ancient scripture forgery and control network",
                "Psychotropic-laced communion ritual ring",
                "False messiah resurrection project",
                "Doomsday astrological alignment plan",
                "Cult-led planetary cleansing doctrine",
                "Secret relic-worshipping assassination cell",
                "Faith-based hostage indoctrination pipeline",
                "Voices-of-the-Serpent transmission station",
                "Pilgrimage disappearance conspiracy",
                "Apocalyptic comet-summoning ritual attempt",
                "Cult-run excommunication death squad",
                "Unholy artifact corruption operation",
                "Deity-appeasement mass sacrifice trial",
                "Soul-harvesting theological experiment",
                "Hostage-taking ransom cartel",
                "Starship hijacking death squad",
                "System-wide extortion and protection racket",
                "Black-flag slave trading network",
                "Pirate-run organ harvesting ring",
                "Contraband warp-lane ambush operation",
                "Terrormorph egg smuggling conspiracy",
                "Deep-space civilian raiding campaign",
                "Corpse looting and identity theft ring",
                "Encrypted pirate broadcast intimidation channel",
                "Forced labor asteroid mine operation",
                "Grav-drive sabotage-for-hire scheme",
                "Black-market weapons augmentation lab",
                "Merciless bounty hunter entrapment plot",
                "Illicit starmap forgery and misdirection racket",
                "Pirate-led colony intimidation regime",
                "False distress beacon ambush plan",
                "Credit laundering through dead freighters",
                "Hostile takeover of frontier refueling stations",
                "Total-systems fear campaign for territory expansion",
                "Illegal cargo skimming ring",
                "Frontier trade lane robbery circuit",
                "Stolen ship parts reselling operation",
                "Unauthorized refueling siphon scheme",
                "Coercive debt collection crew",
                "Dockside intimidation and protection racket",
                "Asteroid miner shakedown network",
                "Counterfeit goods distribution racket",
                "Navigation beacon tampering scam",
                "Sabotage-for-hire starship repair grift",
                "Stolen medical supplies trafficking route",
                "Credit chip duplication workshop",
                "Pirate-run salvage fraud operation",
                "Extorted toll checkpoint in deep space",
                "Hijacked comm relay blackmail ring",
                "Undocumented passenger smuggling line",
                "Stolen fuel cell laundering scheme",
                "Illegal weapons resale market",
                "Freighter tracking and robbery planning hub",
                "Covert data theft and blackmail pipeline",
                "Local caravan ambush crew",
                "Frontier homestead raiding gang",
                "Small-time fuel siphoning ring",
                "Back-road toll extortion group",
                "Crop theft and livestock rustling outfit",
                "Abandoned mine squatters turned raiders",
                "Stolen tool and equipment resale scheme",
                "Frontier shuttle parts stripping crew",
                "Settlement well poisoning intimidation ploy",
                "Outpost burglary and stash-looting spree",
                "Travelers' camp robbery circuit",
                "Local courier interception racket",
                "Blackmailing settlers for water rights",
                "Fence-operated stolen goods pipeline",
                "Illegal hunting and hide trafficking ring",
                "Derelict-ship scrap scavenger gang",
                "Unauthorized salvage claim jumpers",
                "Roadside distress-signal trap crew",
                "Wilderness tracker-mugger group",
                "Small-crew kidnap-for-ransom scheme",
                "Family-run homestead raiding ring",
                "Generational livestock rustling operation",
                "Water siphoning and rights intimidation scheme",
                "Multi-branch kinfolk burglary network",
                "Frontier land-claim squatting dynasty",
                "Backwoods moonshine smuggling line",
                "Illegal hunting grounds enforcement by family enforcers",
                "Credit chip counterfeiting in a farmhouse workshop",
                "Family-led toll checkpoint on remote trade roads",
                "Stolen farm equipment resale racket",
                "Clan-run abduction-for-ransom operation",
                "Rural cargo intercept crew using hidden trails",
                "Outlaw family feud spillover into settlement harassment",
                "Generational salvage-claim forgers",
                "Family-guarded contraband stash caves",
                "Rogue family militia pressuring nearby settlers",
                "Unmarked grave cleanup after ambush operations",
                "Clan-run courier sabotage and package theft",
                "Blackmail through captured family records of locals",
                "Family-operated frontier intimidation patrols",
                "Rural sabotage cell targeting corporate pipelines",
                "Frontier rebels dismantling automated farm drones",
                "Underground movement stealing back overtaxed harvests",
                "Rebel group disabling corporate survey outposts",
                "Family-led strike force attacking land-grab teams",
                "Confiscated corporate equipment redistribution network",
                "Rebel sabotage of automated factory shipments",
                "Backwoods encryption hub leaking internal corporate memos",
                "Rural activists blocking new corporate mining claims",
                "Outlaw family raiding supply convoys feeding corporate expansion",
                "Rebel hackers disrupting corporate water ration controls",
                "Frontier militia resisting forced property buyouts",
                "Clandestine crop-sharing network dodging corporate quotas",
                "Rural ambush crew targeting exploitative contract enforcers",
                "Dissenting settlers hijacking drone patrol routes",
                "Rebel demolition team targeting unapproved corp installations",
                "Family-led resistance distributing banned farming tools",
                "Sabotage squad contaminating corp-exclusive resource caches",
                "Rebel scouts tracking illegal corporate wildlife culls",
                "Underground alliance sheltering settlers evading corp debt collectors"
            };
            var theme = questThemes[random.Next(questThemes.Count)];
            return theme;
        }
        public static string GetConversationIntrigueDetail()
        {
            List<string> details = new()
            {
                "They drop a name in passing — someone they clearly expect you to recognise, but don't explain.",
                "They stop mid-sentence, glance at something behind you, then pretend they didn't.",
                "They answer a question you didn't ask — which means they already knew what you were going to say.",
                "They're very specific about one detail and deliberately vague about everything around it.",
                "They mention a place or date that doesn't quite match what you've been told.",
                "They offer something useful a little too quickly, as if they'd prepared it in advance.",
                "They laugh at the wrong moment — then recover so smoothly it almost reads as natural.",
                "They refer to someone in the past tense, then immediately correct themselves.",
                "They ask a question that only makes sense if they already know the answer.",
                "They clock the exits before they sit down.",
                "They repeat your phrasing back to you slightly changed — testing what you meant.",
                "They're calm about everything except one thing, which they won't look at directly.",
                "They've clearly been in this conversation before, with someone else.",
                "They know who you work for before you mention it.",
                "They give you exactly what you asked for — nothing more, nothing less — like they rehearsed the limit.",
                "They flinch at a name no one in the room should recognise.",
                "There's a gap in their story they don't try to fill — they just wait to see if you notice.",
                "They're friendly, but they never say anything they couldn't walk back.",
                "They know the other person in the room, but they act like they don't.",
                "They end the conversation before it reaches the thing they came to say.",
            };

            return details[RandomProvider.Random.Next(details.Count)];
        }
    }
}
