using System.Collections.Generic;

namespace Retrograde.AI.Utils
{
    public static class NarrativeSeedData
    {
        // Emotional tone for outlaw audio log — picked randomly so each log feels distinct
        public static readonly List<string> LogTones = new List<string>
        {
            "exhausted, paranoid, and afraid — they are not coping; there is no dark humour, no bravado, no uplift",
            "defiant and angry — they don't believe they did anything wrong and want the record to reflect that",
            "hollow and resigned — they've stopped expecting to get out of this; they're marking time, not planning",
            "desperately bargaining with themselves — listing reasons they'll get away with it, convincing no one including themselves",
            "bitter and accusatory — the entire log is an indictment of a specific person they hold responsible for everything",
            "methodical and suppressed — trying hard to stay calm and practical, but fear seeps through every sentence",
            "quietly calculating — composing themselves with precision, already planning the next move as if the current crisis is beneath them",
            "falsely cheerful — forcing an upbeat tone that barely conceals the desperation underneath",
            "detached and clinical — reporting events in the third person as a coping mechanism, as though this is happening to someone else",
            "eerily calm — past the point of panic, speaking slowly and clearly because they have nothing left to lose",
            "self-pitying — cataloguing every injustice they've suffered, convinced no one has ever had it as hard as they do",
            "nostalgic and mournful — drifting between present trouble and memories of better times, unable to stay focused on either",
            "cynical and contemptuous — dismissive of everyone involved, including themselves; nothing surprises them anymore",
            "quietly pleading — not with anyone in particular, just speaking into the void, hoping something changes",
            "erratic and scattered — thoughts jumping between unrelated concerns, clearly not sleeping, barely holding together",
            "guarded and evasive — choosing every word carefully, aware that this recording could be used against them",
            "darkly humorous — making bleak jokes to cope, the laughter never quite reaching their eyes",
            "exhausted but stubborn — too tired to keep going but too proud to stop; every sentence costs them something",
            "confessional and raw — speaking as though to a priest or a therapist, finally saying things they've never admitted aloud",
            "coldly furious — not ranting but seething; each word measured and deliberate, anger buried just beneath the surface",
            "desperate for connection — speaking as though to a specific person who may never hear it, needing someone to understand",
            "philosophical and detached — retreating into abstract thinking as a way of not facing the immediate reality",
            "tightly controlled grief — holding it together by sheer will, the emotion visible only in pauses and word choices",
            "manic and frenetic — speaking too fast, thoughts tumbling over each other, energy that is clearly unsustainable",
            "hollow optimism — insisting things will work out with a conviction that sounds more rehearsed than believed",
            "resigned to consequences but still angry — they know how this ends; they just want someone to hear their side first",
        };

        // What the log is emotionally about — the subject the character keeps returning to
        public static readonly List<string> LogFocusPoints = new List<string>
        {
            "their escape route — what worked, what fell through, and what they're attempting next",
            "a person they had to cut off or leave behind to stay alive",
            "the moment they knew they were finished — a specific decision or event that sealed their fate",
            "the act itself — what they did or took, and why it felt necessary at the time",
            "who they blame, and the case they're building in their own head for why that person is worse than they are",
            "what they plan to do if they somehow get clear of all this",
            "what they believe will happen to them if they're caught",
            "a small routine or habit they've clung to as everything else has fallen apart",
            "a message they composed but never sent — and whether they should still send it",
            "money — how much they need, where it might come from, and how little they actually have left",
            "someone they wronged who didn't deserve it, and who probably never will",
            "a hiding place they've found and how long they think it will hold",
            "the one person who still believes in them, and their fear of destroying that",
            "a decision they keep second-guessing, replaying it differently each time",
            "sleep — the lack of it, the dreams when it comes, and what they'd give for one uninterrupted night",
            "food and basic survival — reduced to worrying about things they never thought about before",
            "their own reflection — how different they look now, and what that says about where they've ended up",
            "a skill or knowledge they have that might be their only remaining leverage",
            "the trail they left behind — what others might find, and how much time they have before it's found",
            "a moment of unexpected kindness from a stranger, and what it stirred in them",
            "their health — an injury, illness, or exhaustion they can no longer ignore",
            "a document, object, or piece of evidence they're still carrying and don't know what to do with",
            "old debts — the ones that started all of this and whether paying them would have changed anything",
            "the version of themselves they wanted to become, and the distance between that and where they are now",
            "a rumour they heard about their own situation — what people are saying, and how wrong or right it is",
            "religion or superstition — whether they still believe in anything, and what they'd ask for if they did",
            "the next twenty-four hours — not further than that, just surviving what's immediately ahead",
            "silence — the absence of the life they had, and how loud that absence is",
        };

        // The type of transmission found on the derelict ship — shapes the AI prompt and tone
        public static readonly List<string> TransmissionTypes = new List<string>
        {
            "a distress beacon set to loop automatically after the crew stopped responding",
            "a personal audio log recorded by a crew member in their final hours aboard the ship",
            "a coded message intended for a contact outside the ship that was never transmitted",
            "a scheduled status report that was recorded but never sent before things went wrong",
            "a warning left by whoever survived longest, hoping someone would eventually board",
            "an emergency broadcast triggered automatically when the ship's crew stopped responding",
            "a private message from a crew member to someone they were trying to protect",
            "a data burst sent to a dead drop that was intercepted and stored to local memory",
            "a fragmented recording recovered from a damaged data slate found near the airlock",
            "a cryptic voice note left as insurance, meant to be found only by the right person",
            "a transmission from a contact trying to reach the crew — saved to the local log because no one answered",
            "a last-resort message recorded by someone who knew they were not getting off the ship",
            "a navigation log update recorded automatically by the ship's AI, noting course changes no one authorised",
            "a maintenance report dictated by a crew member who clearly knew something was wrong but couldn't say it plainly",
            "a brief, unaddressed audio note that sounds like someone talking to themselves to stay calm",
            "a crew morale check-in recorded for the company, suddenly interrupted and never completed",
            "a terse message from the ship's captain to an unnamed contact, flagged priority but never acknowledged",
            "a series of short clips recorded over several days, each one shorter and more frightened than the last",
            "a deposition-style recording made by someone convinced they were about to be killed — and wanted it on record",
            "an intercepted signal from another vessel, stored to local memory when the crew could no longer respond",
            "a burst transmission addressed to a UC registry office, reporting irregularities that were never acted on",
            "a recruitment pitch recorded by someone who clearly no longer believed what they were saying",
            "a log entry from a crew member documenting increasingly strange behaviour from the rest of the crew",
            "a half-finished message to corporate oversight, cut off before the sender could say what they actually knew",
            "a quarantine notification recorded by the ship's medical system, flagging the crew as compromised",
            "a rambling monologue from someone in the final stages of something — fear, illness, or worse",
            "a calm, professional handover note that becomes increasingly strange the longer it goes on",
            "a route confirmation sent by the ship to a relay station that never received a reply",
            "a voice memo from a crew member cataloguing everything of value aboard the ship — recorded the day before the end",
            "a short prayer or personal ritual recorded by someone who had stopped expecting rescue",
            "an automated insurance report triggered by hull damage — the only record of what happened on the ship's final day",
            "a children's rhyme hummed quietly by someone who sounds like they are trying to remember what normal felt like",
        };

        // Who is writing the first-person account found in the world
        public static readonly List<string> SpeakerTypes = new List<string>
        {
            "a co-worker who noticed the target acting strangely before they disappeared",
            "someone who was directly defrauded or harmed by the target",
            "a neighbour or local who witnessed something they couldn't explain",
            "a supervisor who discovered something was missing after the target left",
            "someone who unknowingly helped the target cover their tracks",
            "a local trader or contact who was pressured or threatened by the target",
            "a person who was owed money by the target and never got paid",
            "a friend or associate who is now avoiding questions about the target",
            "someone who shared a workspace with the target and noticed too late",
            "a person who found something the target left behind when they fled",
            "a security contractor brought in after the target disappeared",
            "a former business partner now worried about their own exposure",
            "a child or younger relative who noticed things adults missed",
            "a medic who treated the target for injuries they couldn't explain",
            "someone who received a strange message from the target just before they vanished",
            "a rival who quietly benefited from the target's troubles and feels uneasy about it",
            "a courier who made regular deliveries and noticed things changing",
            "a salvager who found materials at a site that shouldn't have been there",
            "a bartender who overheard conversations they didn't understand at the time",
            "a port official who processed an irregular shipment now linked to the target",
            "a former roommate who noticed unexplained cash and goods appearing",
            "a repair technician who spotted unexplained modifications on the target's equipment",
            "a community leader trying to make sense of what the target did to their settlement",
            "someone the target tried to recruit, who refused and doesn't know what to do with that",
            "a retired law enforcement contact with an old grudge and new evidence",
            "a family member torn between loyalty and the harm the target caused",
            "a bureaucrat who signed off on documents they now deeply regret",
            "an eyewitness who left the area and has been reluctant to speak until now",
            "an automated system log that captured anomalies no one thought to check",
            "a journalist or information broker who has been quietly pulling threads",
            "a dock supervisor who let through a shipment they shouldn't have and has been nervous ever since",
            "a former cellmate who shared quarters with the target during a brief detention neither of them talks about",
            "a translator or interpreter who was present during a conversation they were never supposed to understand",
            "an innkeeper or hostel operator who noticed the target staying too long and asking too many questions",
            "a groundskeeper or custodian who cleaned up after the target and found things they couldn't explain",
            "a fellow traveller on the same shuttle or transport who struck up a conversation they now regret",
            "a former teacher or mentor who recognised something in the target years before the trouble started",
            "a notary or contract witness who stamped documents they now believe were fraudulent",
            "a shopkeeper who extended credit to the target and was never repaid",
            "an anonymous tip left on an official reporting channel — sparse, careful, and clearly written by someone who knows more than they're saying",
            "a gambling partner who won money off the target and is only now wondering where it came from",
            "a night-shift security officer who saw the target enter a restricted area and looked the other way",
            "a food vendor or canteen worker who served the target regularly and noticed when they stopped coming",
            "a former colleague who recommended the target for their last legitimate job and feels responsible",
            "a transit worker who processed the target's travel documents and flagged something they were told to ignore",
            "a cleaner or sanitation worker who found discarded items the target left behind when they fled",
            "a pharmacist or medical supplier who filled an unusual order and has been wondering about it since",
            "someone who witnessed the target doing something unexpectedly kind, which made everything harder to reconcile",
            "a debt collector sent after the target who found only questions where they expected answers",
            "a child who befriended the target without knowing what they were involved in"
        };
    }
}
