using Retrograde;
using System.Collections.Generic;

namespace Retrograde.AI.Utils
{
    public static class NpcSeedData
    {
        public static readonly List<string> Upbringings = new List<string>
        {
            "Grew up in the city of New Atlantis, their parents worked in MAST admin.",
            "Grew up in the city of New Atlantis, their parents worked in the UC Navy.",
            "Grew up in the city of Neon, as a streetrat on the Ebbside.",
            "Grew up in the city of Akila, as an orphan on The Stretch.",
            "Grew up drifting system to system as a spacer kid aboard a family owned hauler.",
            "Grew up in the Well district beneath New Atlantis, scraping by on maintenance work and charity.",
            "Grew up on Cydonia, Mars, as a miner's child in the settlement's lower tunnels.",
            "Grew up in Gagarin Landing, one of the oldest settled colonies — strict, self-sufficient, proud.",
            "Grew up in Ryujin Industries housing blocks in Neon, groomed from childhood for corporate life.",
            "Grew up aboard a Deimos Staryard platform, the child of a shift worker on the hull crews.",
            "Grew up in an Argos Extractors mining camp, one of many faceless workers' kids.",
            "Grew up in a House Va'ruun commune, raised on doctrine and devotion before eventually leaving.",
            "Grew up in the Freestar Collective's rural territories — farming, isolation, and self-reliance.",
            "Grew up in New Atlantis under UC social welfare, shuffled through transitional housing as a child.",
            "Grew up on a remote frontier outpost with no faction affiliation — independent, guarded, capable.",
            "Grew up in Neon's pleasure district, raised by a parent who worked the clubs and casinos.",
            "Grew up in a Trackers Alliance safe house, the child of a bounty hunter who kept moving.",
            "Grew up in a Trade Authority freight depot, surrounded by shipping routes and black-market rumours.",
            "Grew up on a generational farm on Montara Luna under Freestar Collective jurisdiction.",
            "Grew up in a United Colonies military barracks town, where discipline was expected of every child.",
            "Grew up as a ward of Ryujin Industries after their parents died on the job — debt inherited at birth.",
            "Grew up on a ship with no fixed port, the child of independent traders who trusted no faction.",
            "Grew up in Cydonia's commercial district, where deals happened in the margins of legitimate trade.",
            "Grew up in a Crimson Fleet-adjacent port settlement, learning early what not to ask about.",
            "Grew up in a UC Vanguard support town, raised on stories of service and sacrifice.",
            "Grew up in the agricultural belt of Akila's outer settlements, far from the city's politics.",
            "Grew up in a Neon laboratory housing block, the child of a Xenofresh Fisheries technician.",
            "Grew up in a Spacer clan, learning to scavenge, fight, and disappear before they could read.",
            "Grew up in a failed colony attempt — survivors raised them communally after the leadership collapsed.",
            "Grew up in New Atlantis's UC military school program, fast-tracked and discarded before graduation.",
            "Grew up moving between UC and Freestar territory as their parents fled old debts.",
            "Grew up in a backwater port on the edge of Freestar space — lawless, quiet, forgotten.",
            "Grew up in an Ecliptic mercenary base town, where everyone's parent had blood on their hands.",
            "Grew up in a Stroud-Eklund corporate estate — comfortable, monitored, and deeply unhappy.",
            "Grew up on a long-haul ore freighter run between Cydonia and Deimos — born between planets.",
            "Grew up in the slum housing beneath Neon's commercial towers, invisible to the people above.",
            "Grew up in a Freestar Rangers outpost town — idealism was everywhere, until they saw enough to know better.",
            "Grew up in a remote research station, the only child in a crew of scientists who had no idea how to raise one.",
            "Grew up in UC SysDef administrative housing — watched, recorded, and aware of it from an early age.",
            "Grew up as the youngest in a multi-family ship crew that broke up when the credits ran dry.",
            "Grew up in New Atlantis's embassy district, the child of a minor trade diplomat with many enemies.",
            "Grew up in a Reliant Medical outpost clinic, raised by a parent who treated everyone regardless of faction.",
            "Grew up in a starship graveyard settlement — salvage was survival and trust was a luxury.",
            "Grew up as a ward of the Trackers Alliance after their parents were killed by a mark who got away.",
            "Grew up in Akila's merchant quarter — trade, negotiation, and knowing when to walk away.",
            "Grew up on a planet that never made it onto any official registry — not quite legal, not quite forgotten.",
            "Grew up in a House Va'ruun border settlement before the faction sealed its doors to outsiders.",
            "Grew up in a remote UC colony that met with faction conflict — the rubble shaped them.",
            "Grew up in a Neon corporate training program from age six — obedient until the day they stopped being.",
            "Grew up in an old Earth colony remnant settlement — they still kept the old customs alive, barely.",
        };

        public static readonly List<string> FearsAndPhobias = new List<string>
        {
            "Fear of heights",
            "Fear of deep water",
            "Fear of small spaces",
            "Fear of the dark",
            "Fear of being alone",
            "Fear of vacuum — the idea of the void just outside the hull never became ordinary.",
            "Fear of fire in enclosed spaces — they've seen what it does in a pressurised hull.",
            "Fear of crowds — too many faces, too many threats, no clear exit.",
            "Fear of losing their memory — the idea that they could forget who they were terrifies them.",
            "Fear of being watched — the sensation of unseen eyes follows them into sleep.",
            "Fear of betrayal — trusting anyone comes with a low, constant dread they'll regret it.",
            "Fear of silence — it means something is wrong, something stopped, someone isn't coming back.",
            "Fear of medical equipment — a bad experience left a mark that reason can't reach.",
            "Fear of authority figures — not just discomfort, but a visceral shutdown when faced with power.",
            "Fear of being trapped underground — colony tunnels still make them flinch.",
            "Fear of ship depressurisation — they have drilled the procedures so many times they can't stop.",
            "Fear of sleep — what they dream about is worse than staying awake.",
            "Fear of being forgotten — the idea of disappearing without leaving a mark behind haunts them.",
            "Fear of illness — a childhood epidemic left them hypervigilant about any physical symptom.",
            "Fear of running out of air — they count canisters compulsively, even when supply is fine.",
            "Fear of losing control — the possibility of breaking down in public is constant and mortifying.",
            "Fear of being recognised — every crowd contains someone who might know what they did.",
            "Fear of weapons malfunction — they check and recheck before trusting anything mechanical.",
            "Fear of poison — they've been dosed once; now food and drink are approached with caution.",
            "Fear of their own anger — they know what they're capable of and it scares them more than anything.",
            "Fear of commitment — any binding agreement triggers near-panic.",
            "Fear of losing someone they love — they keep everyone at a distance to avoid the arithmetic.",
            "Fear of being wrong — being certain has kept them alive; admitting doubt feels like falling.",
            "Fear of a specific comm tone — a particular alert sound makes their hands shake before they think.",
            "Fear of dying in space — not death itself, but drifting, untethered, where no one finds them.",
            "Fear of biometric checkpoints — they still produce a cold sweat, even with clean papers.",
            "Fear of total darkness with no suit readout — silent black with no data at all.",
            "Fear of Terrormorphs — not the rational kind; the kind that freezes them entirely.",
            "Fear of waking up somewhere unrecognised — disorientation triggers something deeper than anxiety.",
            "Fear of deep-space derelicts — they've been on one and know exactly what they hold.",
            "Fear of being sedated — losing consciousness while others have access to them is intolerable.",
            "Fear of losing their ship — it's not transport, it's the only home they have left.",
            "Fear of specific smells — a particular scent takes them somewhere they can't fully describe.",
            "Fear of numbers running out — credits, oxygen, days left — they count everything obsessively.",
            "Fear of getting comfortable — past experience says comfort is the moment before it falls apart.",
            "Fear of radiation — a close call left them hyperaware of every scanner and warning symbol.",
            "Fear of success — they've sabotaged things before they got too good and know they'll do it again.",
            "Fear of open water on alien worlds — not just drowning, but what might be beneath.",
            "Fear of identity theft or being replaced — paranoia about authenticity runs deep.",
            "Fear of crowds thinning suddenly — when people leave a space fast, something is always wrong.",
            "Fear of lightning and electrical storms — a near-miss during a hull-walk still interrupts sleep.",
        };

        public static readonly List<string> Quirks = new List<string>
        {
            "Never sits with their back to a door.",
            "Counts things under their breath when they're nervous — steps, ceiling tiles, bottles.",
            "Refuses to use their real name, even with people they trust.",
            "Always keeps one hand free, never both in pockets.",
            "Has a tell — touches their collar or jaw when they're lying.",
            "Never eats in a place they haven't scoped out first.",
            "Keeps a specific exit route planned in every room they enter.",
            "Hoards small, specific items — matchbooks, cable ties, painkillers — 'just in case'.",
            "Speaks quietly enough that people have to lean in to hear them.",
            "Won't sleep more than four hours in one place before moving on.",
            "Memorises faces instinctively — can describe someone from a single glance weeks later.",
            "Changes their route every time, never the same path twice.",
            "Keeps a burner comm they've never activated, ready if things go wrong.",
            "Always pays in untraceable scrip, never biometric.",
            "Has a codeword with no one to call it — old habit from a life that no longer exists.",
            "Talks to themselves when alone, running through scenarios out loud.",
            "Wears the same worn item of clothing every day — superstition or comfort, they're not sure.",
            "Flinches at loud, sudden sounds but recovers fast and hates being seen doing it.",
            "Never gives a straight answer to 'where are you headed?'",
            "Reads every room in terms of who could be a threat and in what order.",
            "Leaves food on the plate — old signal habit, now just something they do.",
            "Keeps a handwritten list of names they don't talk about.",
            "Has a ritual before sleep: checks locks, windows, gear. Every night. Even in safe places.",
            "Avoids mirrors when they can — something about seeing themselves clearly unsettles them.",
            "Picks up local accents quickly without noticing, blends in without meaning to.",
            "Moves their lips silently when memorising something — floor plans, faces, names.",
            "Never uses the same alias twice — each new place gets a new name, no exceptions.",
            "Taps a specific pattern on surfaces when thinking — three short, one long.",
            "Carries no identification of any kind. If pressed, produces a forgery they've half-forgotten is fake.",
            "Asks people for the time rather than checking their own comms — old tradecraft habit.",
            "Never sits in direct light if they can avoid it. Booths, corners, shadows.",
            "Keeps a glass in hand at social gatherings but never finishes it — camouflage, not thirst.",
            "Knows exactly what they're carrying at all times — credits, charges, steps to the exit.",
            "Mirrors body language without realising — unconscious mimicry developed to blend in.",
            "Keeps a secondary bag packed and hidden nearby, always, even after months in one place.",
            "Responds to questions with questions, redirecting instinctively before they can catch themselves.",
            "Goes quiet when frightened rather than louder — the stillness is the tell.",
            "Traces the edges of objects with their fingers when thinking — coins, bottles, doorframes.",
            "Watches hands first, face second. Learned that order the hard way.",
            "Maintains a system for remembering which lie they told who — the details stay consistent.",
            "Carries a physical object — a coin, a bolt, a chip — that they touch when they need clarity.",
            "Breathes through a deliberate, practiced pattern under stress and hates being interrupted mid-count.",
            "Scans exits immediately upon entering anywhere, without pausing or breaking conversation.",
            "Never confirms their own name. Lets others fill in what they already believe.",
            "Keeps a mental map of every place they've visited in the last forty-eight hours, updated constantly.",
            "Uses different posture when they think no one is watching — an entirely different way of holding themselves.",
            "Never swears, even under stress — they switched it off once and never switched it back on.",
            "Maintains a friendly, neutral expression that never quite reaches their eyes.",
            "Keeps their back to walls not from paranoia but habit — they stopped noticing years ago.",
            "Has a specific word or phrase that means 'everything is wrong, do not react' — for a partner they no longer have.",
        };

        public static readonly List<string> Nationalities = new List<string>
        {
            "American",
            "British",
            "Canadian",
            "Mexican",
            "Brazilian",
            "French",
            "German",
            "Japanese",
            "Chinese",
            "Russian",
            "Australian",
            "Indian",
            "Nigerian",
            "South African",
            "Egyptian",
            "Ethiopian",
            "Kenyan",
            "Argentinian",
            "Colombian",
            "Chilean",
            "Peruvian",
            "Spanish",
            "Italian",
            "Portuguese",
            "Dutch",
            "Belgian",
            "Swedish",
            "Norwegian",
            "Danish",
            "Finnish",
            "Polish",
            "Czech",
            "Hungarian",
            "Romanian",
            "Greek",
            "Turkish",
            "Israeli",
            "Iranian",
            "Pakistani",
            "Vietnamese",
            "Korean",
            "Filipino",
            "Indonesian",
            "Thai",
            "Singaporean",
            "New Zealander",
            "Irish",
            "Scottish",
            "Moroccan",
            "Algerian",
        };

        public static string GetUpbringing() => Upbringings[RandomProvider.Random.Next(Upbringings.Count)];
        public static string GetFears()      => FearsAndPhobias[RandomProvider.Random.Next(FearsAndPhobias.Count)];
        public static string GetFlaws()      => StorySeedData.PersonalityTraits[RandomProvider.Random.Next(StorySeedData.PersonalityTraits.Count)];
        public static string GetGoals()      => StorySeedData.Motives[RandomProvider.Random.Next(StorySeedData.Motives.Count)];
        public static string GetQuirk()      => Quirks[RandomProvider.Random.Next(Quirks.Count)];
    }
}
