using Retrograde.Nouns;
using Retrograde.Writing;
using Mutagen.Bethesda.Starfield;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Retrograde.Chains.Interfaces
{
    public interface IOutlawQuest
    {
        public Quest Setup(StarfieldMod myMod, OutlawNpc outlawNpc, MissionTemplate missionTemplate, IOutlawQuest nextQuest);
        public string LogMessage { get; set; }
        public string QuestLocation { get; set; }
        public Quest questform { get; set; }

        /// <summary>
        /// Returns all polishable text pieces generated by this quest.
        /// Default: a single QuestLogPolishable wrapping questform (if non-null).
        /// Quests with additional text (books, dialogue) should override this.
        /// </summary>
        public IEnumerable<IPolishable> GetPolishables()
        {
            if (questform != null)
                yield return new QuestLogPolishable(questform);
        }

        /// <summary>
        /// Stages audio for any text this quest deferred during Setup() so the polish
        /// pass could improve it first. Default: no-op. Override in quests that create
        /// voiced books (calling SpeechTools.AddVoice with the current book text).
        /// </summary>
        public void StageAudio() { }
    }
}
