C:\git\FrankyCLI\bin\Debug\net6.0\FrankyCLI.exe avontechshipyards flip f ats_ms_dishs_01 "Avontech Dish"
C:\git\FrankyCLI\bin\Debug\net6.0\FrankyCLI.exe avontechshipyards flip f ats_ms_dishs_03 "Avontech Dish Small"
C:\git\FrankyCLI\bin\Debug\net6.0\FrankyCLI.exe avontechshipyards flip f atsf_ms_hood01 "Avontech Hood"
C:\git\FrankyCLI\bin\Debug\net6.0\FrankyCLI.exe avontechshipyards flip f atsf_ms_hood03 "Avontech Hood"
C:\git\FrankyCLI\bin\Debug\net6.0\FrankyCLI.exe avontechshipyards flip f atsf_ms_hood04 "Avontech Hood"
C:\git\FrankyCLI\bin\Debug\net6.0\FrankyCLI.exe avontechshipyards flip f atsf_ms_keel01 "Avontech Keel"
C:\git\FrankyCLI\bin\Debug\net6.0\FrankyCLI.exe avontechshipyards flip f atsf_ms_keel04 "Avontech Keel"
C:\git\FrankyCLI\bin\Debug\net6.0\FrankyCLI.exe avontechshipyards flip f atsf_ms_nose01 "Avontech Nose"
C:\git\FrankyCLI\bin\Debug\net6.0\FrankyCLI.exe avontechshipyards flip f atsf_ms_nose02 "Avontech Nose"
C:\git\FrankyCLI\bin\Debug\net6.0\FrankyCLI.exe avontechshipyards flip f atsf_ms_nose03 "Avontech Nose"
C:\git\FrankyCLI\bin\Debug\net6.0\FrankyCLI.exe avontechshipyards flip f atsf_ms_nose04 "Avontech Nose"
C:\git\FrankyCLI\bin\Debug\net6.0\FrankyCLI.exe avontechshipyards flip f atsf_ms_nosetech01 "Avontech Nose"
C:\git\FrankyCLI\bin\Debug\net6.0\FrankyCLI.exe avontechshipyards flip f atsf_ms_nosetech02 "Avontech Nose"
C:\git\FrankyCLI\bin\Debug\net6.0\FrankyCLI.exe avontechshipyards flip f atsf_ms_nosetech03 "Avontech Nose"
C:\git\FrankyCLI\bin\Debug\net6.0\FrankyCLI.exe avontechshipyards flip f atsf_ms_nosetech04 "Avontech Nose"
C:\git\FrankyCLI\bin\Debug\net6.0\FrankyCLI.exe avontechshipyards flip f atsf_ms_ring01 "Avontech Ring"
C:\git\FrankyCLI\bin\Debug\net6.0\FrankyCLI.exe avontechshipyards flip f ats_ms_corewing01 "Avontech Corewing"
C:\git\FrankyCLI\bin\Debug\net6.0\FrankyCLI.exe avontechshipyards flip f ats_ms_corewing03 "Avontech Corewing"
C:\git\FrankyCLI\bin\Debug\net6.0\FrankyCLI.exe avontechshipyards flip f ats_ms_corewing05 "Avontech Corewing"
C:\git\FrankyCLI\bin\Debug\net6.0\FrankyCLI.exe avontechshipyards flip f ats_ms_corewing06 "Avontech Corewing"
C:\git\FrankyCLI\bin\Debug\net6.0\FrankyCLI.exe avontechshipyards flip f atsf_ms_glowwing02 "Avontech Corewing"
C:\git\FrankyCLI\bin\Debug\net6.0\FrankyCLI.exe avontechshipyards flip f atsf_ms_glowwing03 "Avontech Corewing"
C:\git\FrankyCLI\bin\Debug\net6.0\FrankyCLI.exe avontechshipyards flip f ats_ms_hullsm01 "Avontech Hull"
C:\git\FrankyCLI\bin\Debug\net6.0\FrankyCLI.exe avontechshipyards flip f ats_ms_hullsm02 "Avontech Hull"
C:\git\FrankyCLI\bin\Debug\net6.0\FrankyCLI.exe avontechshipyards flip f ats_ms_hullsm04 "Avontech Hull"
C:\git\FrankyCLI\bin\Debug\net6.0\FrankyCLI.exe avontechshipyards flip f ats_ms_core01 "Avontech Core"
C:\git\FrankyCLI\bin\Debug\net6.0\FrankyCLI.exe avontechshipyards flip f ats_ms_core02 "Avontech Core"
C:\git\FrankyCLI\bin\Debug\net6.0\FrankyCLI.exe avontechshipyards flip f ats_ms_core03 "Avontech Core"
C:\git\FrankyCLI\bin\Debug\net6.0\FrankyCLI.exe avontechshipyards flip f atsf_ms_halfhood01 "Avontech Half Hood"
C:\git\FrankyCLI\bin\Debug\net6.0\FrankyCLI.exe avontechshipyards flip f atsf_ms_halfring01 "Avontech Half Ring"

C:\git\FrankyCLI\bin\Debug\net6.0\FrankyCLI.exe avontechshipyards yrotate y ats_ms_core01 "Avontech YCore"
C:\git\FrankyCLI\bin\Debug\net6.0\FrankyCLI.exe avontechshipyards yrotate y ats_ms_core02 "Avontech YCore"
C:\git\FrankyCLI\bin\Debug\net6.0\FrankyCLI.exe avontechshipyards yrotate y ats_ms_core03 "Avontech YCore"
C:\git\FrankyCLI\bin\Debug\net6.0\FrankyCLI.exe avontechshipyards yrotate y atsf_ms_hood01 "Avontech YHood"
C:\git\FrankyCLI\bin\Debug\net6.0\FrankyCLI.exe avontechshipyards yrotate y atsf_ms_hood03 "Avontech YHood"
C:\git\FrankyCLI\bin\Debug\net6.0\FrankyCLI.exe avontechshipyards yrotate y atsf_ms_hood04 "Avontech YHood"
C:\git\FrankyCLI\bin\Debug\net6.0\FrankyCLI.exe avontechshipyards yrotate y ats_ms_hullsm02 "Avontech YHull"
C:\git\FrankyCLI\bin\Debug\net6.0\FrankyCLI.exe avontechshipyards yrotate y atsf_ms_halfhood01 "Avontech Half YHood"