using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FrankyCLI.questgen_tools
{
    public class PromptFlavourTools
    {
        public static string AddFlavourToShipBook(string BookPrompt)
        {
            //Flavours that add variation between generations
            List<string> PromptOptions = new List<string>
            {
                "Include hints of romantic tension—unspoken crushes, forbidden relationships, jealousy, or awkward encounters.",
                "Mention a scandalous rumor circulating aboard the ship and how they personally feel about the people involved.",
                "Include vivid details about their daily life on the ship, their private thoughts, and how they feel about recent events.",
                "Incorporate flavorful gossip or rumors they’ve heard about other people encountered during their travels.",
                "Describe sensory details of life aboard the ship—smells, sounds, cramped quarters, rituals.",
                "Reveal an internal conflict or personal dilemma they are struggling with, showing how it shapes their decisions and mood.",
                "Describe their relationships with specific crew members—alliances, grudges, secrets, or unspoken tensions.",
                "Let their cultural background, upbringing, or past experiences influence how they interpret events and express themselves.",
                "Give their writing a distinctive verbal style—slang, metaphors, pacing, or quirks that reflect who they are.",
                "Have them reflect on a recent incident aboard the ship or during their travels, revealing how it affected them personally.",
                "Include subtle hints of unease, suspicion, or foreshadowing about something they believe is about to happen.",
                "Allow moments of honest vulnerability—fears, regrets, insecurities—that they would only admit in a private diary.",
                "Add small worldbuilding details such as customs, slang, ship traditions, or local myths they’ve encountered.",
                "Include mentions of their personal goals, ambitions, or hidden desires, and how the journey affects their pursuit of them.",
                "Describe how the environment affects them physically—fatigue from long shifts, discomfort from ship movement, or reactions to alien climates.",
                "Suggest that someone aboard the ship might be sabotaging others, spreading lies, or hiding a betrayal.",
                "Describe any power struggles, favoritism, or political maneuvering happening within the crew ranks.",
                "Include a moment where someone had an emotional outburst—anger, tears, panic—and explain the fallout.",
                "Highlight social tensions between crew factions, cliques, or individuals who simply can’t stand each other.",
                "Show how misunderstandings or half-heard conversations have sparked distrust or paranoia among the crew.",
                "Include petty rivalries—competition over duties, attention, rank, or even trivial things like cabin space.",
                "Have them reveal a secret they overheard or discovered accidentally—something they know could cause trouble if exposed.",
                "Include an awkward or embarrassing interaction with someone they’re attracted to, and their overthinking afterward.",
                "Have them struggle with unrequited love or uncertainty about whether their feelings are returned.",
                "Let memories of a past lover influence how they view new relationships or romantic opportunities.",
                "Hint at secret late-night conversations or hidden rendezvous away from prying eyes on the ship.",
                "Capture their emotional confusion—torn between desire, duty, fear, or loyalty—regarding someone they care for.",
                "Have them reflect on a strained or complicated relationship with a parent and how it affects their choices today.",
                "Mention ongoing or unresolved rivalry with a sibling—competition, bitterness, or jealousy that still lingers.",
                "Describe the pressure of family expectations weighing on them and their fear of disappointing those back home.",
                "Include memories of arguments or ideological clashes with older family members that shaped their worldview.",
                "Have them hint at a dark or embarrassing family secret they fear others might discover.",
                "Describe an estranged family member they haven’t spoken to in years, along with guilt or resentment about the silence.",
                "Include the burden of inheriting a family legacy—duties, debts, curses, or a name they struggle to live up to.",
                "Show their anxiety about family members far away—illness, danger, conflict—and their helplessness being unable to assist.",
                "Have them react to receiving unexpected family news—a letter, rumor, or message—that stirs old wounds.",
                "Have them describe the everyday chores or repetitive tasks they performed today and how tedious or oddly satisfying they found them.",
                "Include small annoyances—misplaced tools, squeaky doors, lukewarm meals, or a crew member’s irritating habits.",
                "Have them comment on the day’s weather or ship conditions and how it subtly influenced their mood.",
                "Mention simple, routine interactions—brief conversations, polite nods, shared meals—that give a sense of normalcy.",
                "Describe mundane self-care: cleaning clothes, patching gear, trimming hair, or trying to get some decent sleep.",
                "Have them note what they ate or drank today, how it tasted, and any small pleasures or disappointments.",
                "Have them describe a personal or family tradition they try to uphold even while far from home, and how it comforts them.",
                "Include a memory of a cultural ritual or celebration they miss, reflecting on how different it feels to be away during that time.",
                "Have them participate in a small shipboard tradition—old, improvised, or silly—and note how it strengthens crew camaraderie.",
                "Describe a tradition unique to their homeland, and how others react when they explain or attempt to recreate it.",
                "Include a moment where they break a long-standing tradition, willingly or not, and wrestle with the guilt or freedom that follows.",
                "Have them reflect on a tradition they once disliked but now cherish, realizing how much it shaped their identity.",
                "Describe them teaching someone else a tradition, passing down knowledge that feels fragile but important to preserve.",
                "Include a reflection on a tradition that has changed over time, and their struggle to accept or reject this new version of it.",
                "Have them question whether certain traditions still serve a purpose, or if they continue only out of habit or pressure.",
                "Describe a newly emerging tradition aboard the ship, something small but meaningful that helps the crew feel like a family.",
                "Include minor logistical tasks—inventory checks, paperwork, reorganizing supplies, running slow errands around the ship.",
                "Have them describe cleaning or organizing their bunk space, noting small frustrations or tiny comforts they discovered.",
                "Include a mention of them waiting in a long line—mess hall, supply depot, or wash station—and their thoughts while idling.",
                "Describe them dealing with a mildly broken item—stuck locker, jammed drawer, loose hinge—and their attempt to fix or ignore it.",
                "Have them comment on doing basic personal grooming—trimming nails, combing hair, or cleaning boots—and how oddly calming or boring it felt.",
                "Include a moment where they search for a misplaced everyday item and grumble about how often this seems to happen.",
                "Describe them washing or mending a piece of clothing, noticing stains, tears, or smells picked up during the day.",
                "Have them note the repetitive sounds around them—dripping pipes, humming engines, footsteps in the corridor—and how they blend into routine life.",
                "Include a short reflection on a dull shift where nothing noteworthy happened, yet they found themselves daydreaming anyway.",
                "Mention a simple shared meal with the crew, focusing on the plain food, casual chatter, and comfortable ordinariness of it.",
                "Have them question whether they are becoming the person they once hoped to be, revealing doubts or pride in their growth.",
                "Include a moment where they analyze their recent decisions, wondering if they acted out of fear, desire, or obligation.",
                "Have them reflect on a personal flaw they’ve noticed—impatience, jealousy, pride—and how it affects their relationships.",
                "Describe them contemplating a past mistake that still haunts them, and what they would do differently if given the chance.",
                "Include a reflection on what they truly value—loyalty, freedom, safety, adventure—and how the journey tests those beliefs.",
                "Have them assess their emotional state, noting what has changed within them over time and what remains stubbornly the same.",
                "Include thoughts about whether they deserve the good or bad things happening around them, revealing guilt or gratitude.",
                "Have them compare who they were before the voyage to who they are now, acknowledging subtle or dramatic shifts in identity.",
                "Describe them wrestling with uncertainty about their future, questioning where they belong and what purpose they serve.",
                "Have them reflect on a moment of unexpected joy, comfort, or peace, and how rare or precious such moments feel to them.",
                "Have them recognize a small moment of peace or comfort that made them feel like they’re finally beginning to heal.",
                "Include a reflection on someone who has recently helped them emotionally, even in ways they didn’t expect.",
                "Describe them forgiving themselves for a past mistake, or at least taking the first uncertain steps toward forgiveness.",
                "Have them acknowledge progress they’ve made—subtle changes in how they react, think, or cope compared to before.",
                "Include a moment where they let go of something they’ve been clinging to—anger, guilt, fear—and feel lighter for it.",
                "Have them realize they no longer feel as alone as they once did, thanks to new bonds or gentle kindness from others.",
                "Describe them embracing vulnerability, allowing themselves to feel sadness or hope without judgment.",
                "Have them reflect on advice someone gave them, recognizing that it brought clarity or comfort when they needed it most.",
                "Include a realization that they deserve happiness or healing, even if accepting that truth still feels strange.",
                "Have them acknowledge that healing does not mean forgetting, and that some wounds still ache even as they begin to close.",
                "Include a moment where they accept a painful truth about themselves, realizing that facing it is the only way forward.",
                "Describe them confronting a memory they’ve avoided, letting it hurt so it can finally lose some of its power over them.",
                "Have them realize that some relationships cannot be repaired, and the grief of that acceptance becomes part of their healing.",
                "Include a reflection on how suffering has reshaped them, leaving marks they may never erase but can learn to live with.",
                "Have them find strength in surviving something that once broke them, even if the pride feels uncomfortable or undeserved.",
                "Describe them letting go of a hope that has long tormented them, finding grim relief in finally releasing it.",
                "Have them face the consequences of their own actions, accepting responsibility as a painful but necessary step toward growth.",
                "Include a moment where they recognize that healing sometimes feels like numbness, and wonder if that’s progress or simply survival.",
                "Have them admit that they are still angry or afraid, but that these emotions no longer rule them the way they once did.",
                "Have them notice a small habit or ritual that has quietly helped them cope—journaling, breathing, watching the stars—and how it soothes them.",
                "Describe them getting briefly annoyed or amused by something trivial, such as a crewmate’s loud chewing or mismatched socks."
            };
            Random random = new Random();

            int count = 1 + random.Next(5);

            var selected = PromptOptions
                .OrderBy(x => random.Next())
                .Take(count);

            foreach (var prompt in selected)
            {
                BookPrompt += prompt + " ";
            }

            return BookPrompt;
        }

        public static string AddFlavourToGangBook(string BookPrompt)
        {
            //Flavours that add variation between generations
            List<string> PromptOptions = new List<string>
            {
                "Include hints of romantic tension—unspoken crushes, forbidden relationships, jealousy, or awkward encounters.",
                "Have them describe the unspoken rules everyone in the gang learns quickly, and the price of breaking them.",
                "Include a moment where they reflect on the constant tension of never knowing who to trust within their own crew.",
                "Have them mention the daily grind of lookouts, courier runs, and waiting for orders that might never come.",
                "Include a detail about shared scavenged meals, patched clothes, or improvised gear that defined their day-to-day life.",
                "Have them recall the pressure to act tougher than they felt, knowing weakness could be exploited instantly.",
                "Include a moment where they describe the strange loyalty formed through dangerous jobs and sleepless nights.",
                "Have them reflect on crew arguments that flared over small things but carried real consequences.",
                "Include a memory of the gang’s hangout—a cramped hideout, abandoned warehouse, or makeshift base—filled with personal graffiti.",
                "Have them describe early tasks they were given to prove themselves, mundane at first but always risky.",
                "Include a moment where they admit how boredom and fear blended together during long stakeouts or watch shifts.",
                "Have them recall someone in the gang who tried to mentor them, for better or worse.",
                "Include details about the gang’s internal hierarchy—who barked the orders, who enforced them, and who ignored them.",
                "Have them remember the constant movement from one safe spot to another, always staying ahead of rival crews.",
                "Include a moment where they describe celebrations after a successful run—loud, chaotic, and fleeting.",
                "Have them mention the paranoia that came with knowing betrayal was always a possibility.",
                "Include details about coded messages, signs, or phrases the gang used to communicate quietly.",
                "Have them recall the mix of pride and fear that came with being recognized by other crews.",
                "Include a moment where they describe patching up injuries with whatever supplies were available.",
                "Have them reflect on how violence became routine, something they stopped questioning over time.",
                "Include a detail about the gang’s symbol, colors, or calling card, and what it meant to them personally.",
                "Have them recall how violence slowly became the first solution to every problem, even the small ones.",
                "Include a moment where they admit waking up each day unsure if someone in the gang planned to eliminate them.",
                "Have them describe the normalization of cruelty—how beatings, threats, and intimidation became everyday background noise.",
                "Include a reflection on a job that went too far, something they still replay in their mind even if they pretend otherwise.",
                "Have them recall how rival crews weren’t the only threat—their own allies were often just as dangerous.",
                "Include a detail about a night where no one slept, everyone armed, waiting for a betrayal they knew was coming.",
                "Have them describe how new recruits were tested with tasks meant to break them emotionally or physically.",
                "Include a memory of someone who disappeared after questioning orders, and how no one dared to ask why.",
                "Have them reflect on how the line between survival and savagery grew thinner with every passing week.",
                "Include a moment where they realized they were becoming someone they once feared.",
                "Have them describe the constant pressure to prove loyalty, even when it meant hurting someone they cared about.",
                "Include a detail about punishments others received—left as examples to keep the rest compliant.",
                "Have them recall the dread that came every time the boss summoned them, unsure if it was a job or an execution.",
                "Include a memory of a place the gang used for ‘discipline,’ and how just walking past it tightened their chest.",
                "Have them admit that trust became impossible, and friendships were masks worn until convenience ran out.",
                "Include a detail about the paranoia that settled over the gang after a failed job, everyone suspecting everyone.",
                "Have them reflect on how they stopped feeling guilt after a while, replaced by numb acceptance.",
                "Include a moment where they realized leaving the gang wasn’t freedom—it was a death sentence with a longer timer.",
                "Have them describe the ritual of disposing evidence or cleaning after violence, treated like housekeeping.",
                "Include a reflection on how laughter in the gang was never joyful—always sharp, mocking, or edged with menace.",
                "Have them recall intrusive memories that surface at random, reminders of moments they wish they could forget.",
                "Include a moment where they admit loud noises or sudden movements still trigger instinctive fear responses.",
                "Have them reflect on how they struggle to sleep, their mind replaying nights filled with threats and violence.",
                "Include a detail about how certain places or smells bring back memories they'd rather bury.",
                "Have them describe guilt that clings to them, even for actions they were ordered to do.",
                "Include a moment where they realize they flinch when someone raises their voice, no matter who it is.",
                "Have them reflect on the emotional numbness they developed to survive, now hard to shed.",
                "Include a memory of someone they lost in the gang, and the unresolved grief that lingers.",
                "Have them describe how they avoid forming close connections, afraid of betrayal repeating itself.",
                "Include a moment where they face the fear that they are still capable of the person they were forced to become.",
                "Have them admit they struggle to trust anyone's motives, even when no danger exists.",
                "Include a detail about nightmares that revisit old scenes with cruel clarity.",
                "Have them recall how being constantly watched and judged rewired their sense of safety.",
                "Include a reflection on how their moral compass shattered, and how hard it is to rebuild.",
                "Have them describe how their body still reacts before their mind—fight, flee, freeze—long after leaving the gang.",
                "Include a moment where they question if they even deserve peace after everything they've done.",
                "Have them reflect on how isolation became easier than risking emotional vulnerability again.",
                "Include a detail about the physical aches or scars that serve as constant reminders of past brutality.",
                "Have them describe struggling with anger or panic that erupts from nowhere, rooted in old conditioning.",
                "Include a moment where they realize healing doesn't erase what happened—it only teaches them to carry it differently.",
                "Have them recall a moment where love and fear blurred together, unsure whether the warmth they felt was genuine or manipulated.",
                "Include a memory of a kiss shared at the wrong time in the wrong place, shadowed by guilt they still carry.",
                "Have them remember how their lover’s promises always felt too sharp, edged with unspoken threats or expectations.",
                "Include a moment where they realized the person they adored could hurt them—and that part of them didn’t walk away.",
                "Have them recall a whispered confession made in a dark room, one that changed the course of their lives forever.",
                "Include a memory of a fight that turned too intense, each word cutting deeper than either intended.",
                "Have them remember laughing together while knowing deep down that the world was closing in on them.",
                "Include a moment where they held hands not out of affection, but because danger forced them closer.",
                "Have them recall a night spent hiding, pressed close for safety, feeling both connected and terrified.",
                "Include a memory of realizing they were lying to protect someone they loved—and how natural the lie felt.",
                "Have them remember a tender moment overshadowed by the fear that it might be the last they shared.",
                "Include a memory of seeing their lover covered in someone else's blood, and feeling a confusing mix of horror and concern.",
                "Have them recall how jealousy twisted their relationship, turning small disagreements into emotional minefields.",
                "Include a moment where they trusted their lover with a secret they swore never to tell, and still wonder if it was a mistake.",
                "Have them remember watching their lover walk away after a heated argument, unsure if either of them would survive the fallout.",
                "Include a memory of a stolen moment of peace in the middle of chaos, knowing it couldn’t last.",
                "Have them recall the dangerous thrill of planning something reckless together, united in desperation.",
                "Include a moment where they saw the darker side of their lover’s nature—and recognized a reflection of their own.",
                "Have them remember holding someone they loved as everything around them collapsed, love and loss tangled together.",
                "Include a memory of realizing their love was as destructive as it was intoxicating, and being unable to let go.",
                "Have them reflect on how they kept apologizing for things that were never their fault to begin with.",
                "Include a moment where they admit the relationship felt like walking on broken glass—careful, silent, and always afraid.",
                "Have them recall how affection was given and taken away like a reward, shaping their behavior without them noticing.",
                "Include a memory of constantly trying to fix things, even though the other person never met them halfway.",
                "Have them reflect on how arguments always looped back to their supposed failures, regardless of the truth.",
                "Include a moment where they realize they lied to friends just to protect the image of their partner.",
                "Have them recall a time they felt relieved rather than loved when things were briefly calm.",
                "Include a reflection on the fear of speaking honestly, knowing honesty often sparked punishment.",
                "Have them remember how apologies from their partner came drenched in excuses rather than change.",
                "Include a moment where they admit they stayed because leaving felt more terrifying than enduring the pain.",
                "Have them reflect on how isolation became normal—cutting off others because it was easier than the conflict it caused.",
                "Include a memory of their partner twisting past conversations to make them doubt their own perception.",
                "Have them recall how they tried to earn love that should have been freely given.",
                "Include a reflection on how small joys were overshadowed by constant dread of the next argument.",
                "Have them remember realizing that compliments felt like traps, always followed by criticism.",
                "Include a moment where they reflect on how their partner’s needs always consumed their own, slowly erasing their identity.",
                "Have them recall the exhaustion of never being enough, no matter how hard they tried.",
                "Include a reflection on how control was disguised as protection, leaving them suffocated instead of safe.",
                "Have them remember how each attempt to leave was met with promises that shattered within days.",
                "Include a moment where they acknowledge the hardest truth: the relationship broke them long before it officially ended.",
                "Have them recall a boring part-time job they once held, complete with repetitive tasks and forgettable coworkers.",
                "Include a memory of running small errands for family or neighbors, never imagining how different life would become.",
                "Have them remember lazy afternoons spent sitting on a stoop, watching people pass by with no real plans of their own.",
                "Include a moment where they talk about saving loose credits for weeks just to buy something simple.",
                "Have them recall a favorite snack or drink they used to grab from a corner shop on the way home.",
                "Include a detail about an old hobby—fixing small gadgets, sketching, or playing cheap games—to pass the time.",
                "Have them remember a familiar bus or shuttle route they rode daily, always staring out the same window.",
                "Include a moment where they talk about helping out at a family business or doing chores without much thought.",
                "Have them recall hanging out with friends in forgotten places—parking lots, rooftops, old parks—with nothing to do.",
                "Include a memory of a cheap apartment or cramped room they once lived in, messy but harmless.",
                "Have them describe a part-time gig they never expected to lead anywhere—delivering packages, sweeping floors, stocking shelves.",
                "Include a reflection on idle conversations they used to have about dreams they never really believed in.",
                "Have them remember a noisy neighbor, a leaky faucet, or some petty annoyance that felt like the biggest problem at the time.",
                "Include a moment where they talk about going to bed early because there was nothing else to stay up for.",
                "Have them recall listening to music or local radio broadcasts to fill the silence of quiet evenings.",
                "Include a memory of waiting in long lines—at shops, clinics, stations—just part of normal life.",
                "Have them describe the dull rhythm of school or training days, skipping classes more out of boredom than rebellion.",
                "Include a moment where they talk about a place they used to hang out after school—a diner, a stairwell, an empty lot.",
                "Have them recall patching up old clothes or hand-me-downs, not out of hardship but routine.",
                "Include a reflection on how predictable everything felt back then, every day blending into the next without consequence.",
                "Have them recall the first time they were asked to run a small ‘favor’ that didn’t feel entirely legal.",
                "Include a moment where they noticed how often they gravitated toward people with rougher reputations.",
                "Have them remember skipping responsibilities to hang around older kids who always had money and never said how.",
                "Include a memory of being praised for keeping quiet about something they shouldn’t have seen.",
                "Have them recall feeling oddly proud the first time someone called them ‘reliable’ for a risky errand.",
                "Include a moment where they realized they liked the thrill of getting away with something minor.",
                "Have them reflect on how they started spending more time in parts of town where trouble was common.",
                "Include a memory of witnessing a small crime and feeling fascination instead of fear.",
                "Have them recall noticing how quickly they learned the unspoken rules of the street.",
                "Include a moment where they accepted a gift that clearly wasn’t bought—but didn’t ask questions.",
                "Have them remember running with a crowd that always seemed one argument away from violence.",
                "Include a reflection on how they started lying to family or friends about where they were going.",
                "Have them recall how arguments at home made the pull of the streets feel stronger and more welcoming.",
                "Include a memory of the first time someone offered them protection in exchange for loyalty.",
                "Have them describe the subtle excitement of being included in conversations they knew were dangerous.",
                "Include a moment where they realized they could intimidate someone—and found it disturbingly empowering.",
                "Have them reflect on how they ignored early warnings from people who saw the shift in them.",
                "Include a memory of skipping school or work to follow someone who later became a major influence.",
                "Have them recall a moment where a seemingly harmless decision put them on someone’s radar.",
                "Include a moment where they admit that part of them always wanted to belong somewhere—no matter the cost."
            };
            Random random = new Random();

            int count = 1 + random.Next(5);

            var selected = PromptOptions
                .OrderBy(x => random.Next())
                .Take(count);

            foreach (var prompt in selected)
            {
                BookPrompt += prompt + " ";
            }

            return BookPrompt;
        }

        public static string AddFlavourToTargetBook(string BookPrompt)
        {
            //Flavours that add variation between generations
            List<string> PromptOptions = new List<string>
            {
                "Include hints of romantic tension—unspoken crushes, forbidden relationships, jealousy, or awkward encounters.",
                "Include a moment where they recognize that healing sometimes feels like numbness, and wonder if that’s progress or simply survival.",
                "Include a moment where they admit they can no longer tell who they can trust, convinced someone close is plotting against them.",
                "Have them describe hearing whispers or movements they can’t explain, certain someone is watching from the shadows.",
                "Include a reflection on documents or messages they found that don’t add up, leading them to suspect a hidden conspiracy.",
                "Have them express fear that their communications are being intercepted, forcing them to write cautiously or cryptically.",
                "Include a moment where they second-guess an ally’s kindness, wondering if it’s genuine or a calculated trap.",
                "Have them obsess over patterns—footsteps, schedules, odd glances—convinced these small signs reveal a threat.",
                "Include a mention of sleepless nights where every creak or rustle feels like someone approaching them.",
                "Have them question whether their enemies are already within their circle, hiding behind familiar faces while plotting.",
                "Include a fleeting thought that even their own memories might be altered or unreliable, leaving them unsure what is real.",
                "Have them describe the growing certainty that someone is always one step ahead of them, anticipating their every move.",
                "Have them confess that their personal relationships are falling apart faster than they can hold them together.",
                "Have them justify their actions as necessary, insisting no one else had the courage to do what they did.",
                "Include a moment where they argue that the world forced their hand, leaving them no choice but to act as they have.",
                "Have them claim that everyone judging them would have done the same in their situation—if they were honest.",
                "Include a reflection where they paint themselves as a misunderstood hero rather than a villain.",
                "Have them insist that their so-called crimes were actually acts of survival, not malice.",
                "Include a moment where they blame others for pushing them to extremes, absolving themselves of responsibility.",
                "Have them argue that their victims were complicit in their own downfall, one way or another.",
                "Include a justification that rules and laws are tools of the weak, and they refuse to be limited by them.",
                "Have them reframe their betrayals as strategic necessities rather than moral failings.",
                "Include a moment where they claim the ends always justify the means—especially when they are the one deciding the ends.",
                "Have them insist that anyone who opposes them simply doesn’t understand their brilliance or vision.",
                "Include a reflection where they portray themselves as the only one capable of making the hard decisions.",
                "Have them accuse others of hypocrisy, claiming they’re merely more honest about doing what needs to be done.",
                "Include a moment where they rewrite past events to cast themselves as the victim of unfair judgment.",
                "Have them justify cruelty as discipline, claiming it forges stronger people around them.",
                "Include a moment where they argue that mercy would have caused more harm than their harsh choices.",
                "Have them claim that fate or destiny chose them, and therefore their actions are beyond ordinary morality.",
                "Include a justification that power naturally belongs to those willing to seize it.",
                "Have them insist that their enemies brought their fate upon themselves by standing in the way.",
                "Include a reflection where they convince themselves that those they hurt were obstacles, not people.",
                "Have them reinterpret betrayal as liberation—freeing others from their own misguided paths.",
                "Include a moment where they claim that if they hadn’t acted, someone worse would have.",
                "Have them assert that their intelligence places them above conventional ethical constraints.",
                "Include a justification that loyalty is overrated, and only results truly matter.",
                "Have them insist that anyone calling them dangerous simply fears what they don’t understand.",
                "Include a moment where they frame manipulation as guidance, claiming others needed their direction.",
                "Have them argue that their selfishness is actually a form of clarity others lack.",
                "Include a reflection where they celebrate their ruthlessness as a virtue in a broken world.",
                "Have them claim that regret is pointless because every choice they made was the correct one.",
                "Include a moment where they confidently declare that history will vindicate them, even if no one else will.",
                "Have them describe how their morals have slowly eroded, and how disturbingly easy it has become to cross new lines.",
                "Include a moment where they feel a thrill from doing something they once believed was wrong, recognizing how far they've fallen.",
                "Have them admit that harming others no longer bothers them the way it used to, and wonder when that shift happened.",
                "Include a reflection where they take pride in manipulation or cruelty, seeing it as a sign of strength rather than decay.",
                "Have them justify exploiting the vulnerable, claiming that weakness exists to be used.",
                "Include a moment where they recognize the person they used to be—and feel nothing but contempt for that version of themselves.",
                "Have them describe ignoring their conscience so many times that it eventually stopped speaking to them.",
                "Include a reflection where they acknowledge they now measure right and wrong by convenience rather than principle.",
                "Have them recount a moment when they enjoyed watching someone suffer, realizing they no longer pretend to care.",
                "Include a moment where they see someone else’s morality as naive and mock them for it, openly or internally.",
                "Have them admit they’ve grown addicted to power, control, or fear, and feel hollow without it.",
                "Include a description of how they've started treating people as tools or obstacles rather than human beings.",
                "Have them realize they crossed a moral line long ago—and now keep running just to avoid facing it.",
                "Include a moment where they twist morality into a weapon, using it only when it benefits them.",
                "Have them confess that corruption was not a fall, but a choice they embraced willingly.",
                "Include a reflection where they measure their worth by how effectively they can break or bend others.",
                "Have them describe how guilt has faded into numbness, leaving them free to act without hesitation.",
                "Include a moment where they look at an innocent person and feel nothing but opportunity.",
                "Have them acknowledge that they now fear redemption—not because it seems impossible, but because they no longer want it.",
                "Include a moment where they catch themselves savoring the thought of crossing an even darker line next.",
                "Have them describe a moment where they inflicted pain simply to see how someone would react, and felt a cold satisfaction.",
                "Include a reflection where they admit they’ve grown curious about how far they can push someone before they break.",
                "Have them recount a time they watched someone suffer and chose not to intervene, savoring the power it gave them.",
                "Include a moment where they justify their cruelty as a lesson others needed to learn.",
                "Have them describe enjoying the fear in someone’s eyes, recognizing it as proof of their control.",
                "Include a reflection where they admit hurting others has become easier—almost routine.",
                "Have them recall a moment when someone begged for mercy, and how denying it made them feel powerful.",
                "Include a moment where they test how much cruelty they can disguise as necessity.",
                "Have them describe harming someone not out of anger or strategy, but pure curiosity.",
                "Include a reflection where they acknowledge they could have been kind, and deliberately chose not to be.",
                "Have them recount a situation where they exploited someone's vulnerability with calculated precision.",
                "Include a moment where they mock someone’s pain, seeing it as weakness rather than something to empathize with.",
                "Have them describe taking pleasure in ruining someone’s hopes or plans, just to watch their reaction.",
                "Include a reflection where they recognize that others fear them—and secretly enjoy that fear.",
                "Have them recount deliberately manipulating someone into harming themselves emotionally or physically.",
                "Include a moment where they admit cruelty has become a habit, something they perform without thinking.",
                "Have them describe feeling bored when people obey, craving the challenge of breaking those who resist.",
                "Include a reflection where they enjoy withholding something—information, help, comfort—just to watch someone struggle.",
                "Have them recount a moment where they escalated conflict intentionally, savoring the chaos it caused.",
                "Include a moment where they acknowledge that kindness feels foreign now, replaced entirely by sharp, predatory instincts.",
                "Have them cite philosophical ideas to justify their actions, convincing themselves that morality is subjective anyway.",
                "Include a moment where they claim that human behavior is driven by instinct, freeing themselves from responsibility.",
                "Have them reflect on the idea that suffering builds character, using it to excuse what they’ve done to others.",
                "Include a justification that people create their own misery, and they merely accelerate the inevitable.",
                "Have them use psychological theories to explain away their cruelty as a natural coping mechanism.",
                "Include a moment where they reinterpret their selfishness as healthy self-preservation, grounded in ‘rational’ thinking.",
                "Have them claim that empathy is a social construct and that freeing themselves from it brings clarity.",
                "Include a reflection where they argue that purpose and meaning are illusions, making any action permissible.",
                "Have them twist philosophical teachings into excuses for manipulation or betrayal.",
                "Include a moment where they insist that everyone is ruled by unconscious impulses, so blaming themselves is pointless.",
                "Have them justify their actions through a belief in determinism, insisting they had no real choice anyway.",
                "Include a reflection where they adopt a nihilistic worldview to distance themselves from guilt or consequences.",
                "Have them use armchair psychology to diagnose others’ flaws, avoiding scrutiny of their own behavior.",
                "Include a moment where they claim that morality evolves, and they’re simply ahead of everyone else ethically.",
                "Have them convince themselves they are conducting ‘experiments’ on human nature rather than harming people.",
                "Include a reflection where they argue that emotional detachment is a sign of enlightenment rather than decay.",
                "Have them justify manipulation as a form of guiding others toward their ‘true potential.’",
                "Include a moment where they use philosophical paradoxes to muddy their own sense of right and wrong.",
                "Have them claim that guilt is merely a conditioned response, one they have successfully outgrown.",
                "Include a reflection where they reframe their darkest impulses as authenticity—being true to their ‘real self.’",
                "Include a moment where they realize they’ve pushed someone important away without meaning to, and now regret it deeply.",
                "Have them describe how constant stress is making them lash out at people they care about, even when they don’t want to.",
                "Include a reflection on how their old routines, comforts, or joys no longer feel like they belong to them.",
                "Have them admit they no longer recognize the person they’re becoming, and fear it’s too late to turn back.",
                "Include a moment where they try to contact someone they love, only to realize they have no idea what to say anymore.",
                "Have them describe the painful moment they understood a relationship they valued has quietly died over time.",
                "Include a realization that their work, choices, or obsessions have consumed everything else in their life.",
                "Have them hide their guilt behind lofty quotes or theories, hoping complex words will distract from simple wrongdoing.",
                "Include a moment where they speak in grand academic tones to make their actions sound profound rather than cruel.",
                "Have them overanalyze trivial details to appear intelligent, avoiding the emotional truth beneath their behavior.",
                "Include a reflection where they bury remorse under layers of abstract reasoning, pretending depth where none exists.",
                "Have them use obscure terminology to make others doubt whether they even understand the situation well enough to blame them.",
                "Include a moment where they frame their harmful choices as part of a ‘greater intellectual framework,’ masking their insecurity.",
                "Have them pretend to be above ordinary morality by referencing philosophers they barely understand.",
                "Include a reflection where they nitpick semantics to avoid admitting fault, turning guilt into a debate instead of a confession.",
                "Have them insist that only the ‘enlightened’ can comprehend their motives, using pretension to dodge accountability.",
                "Include a moment where they drown their conscience in pedantic arguments, hoping complexity will smother the truth.",
                "Have them confess they’ve been hiding their struggles from everyone, terrified that vulnerability will break what little they have left.",
                "Include a moment where they reflect on how loneliness crept in slowly, until it became the only constant in their life.",
                "Have them reminisce about the simple routines they once had—morning habits, favorite foods, or quiet hobbies.",
                "Include a moment where they recall a job they used to do, unremarkable but steady, and how different life felt then.",
                "Have them describe a familiar street, shop, or café they visited regularly before everything changed.",
                "Include a reflection on an old friend or coworker they lost touch with long before turning to crime.",
                "Have them recall the mundane frustrations of their old life—long lines, broken appliances, nosy neighbors.",
                "Include a moment where they remember saving up for small purchases, appreciating every coin.",
                "Have them describe a favorite place they used to relax, simple and ordinary, now impossibly distant.",
                "Include a memory of chores or tasks they used to complain about, now seeming strangely comforting in hindsight.",
                "Have them recall a hobby they once practiced—gardening, tinkering, reading—that grounded them.",
                "Include a moment where they reflect on old clothes, tools, or belongings they left behind without meaning to.",
                "Have them describe a daily commute they once found boring, now almost nostalgic in its predictability.",
                "Include a memory of cooking simple meals or sharing them with someone before their life unraveled.",
                "Have them recall an ordinary responsibility they had—taking care of a pet, paying bills, fixing leaks.",
                "Include a moment where they remember casual conversations with neighbors or acquaintances they barely knew.",
                "Have them describe the feeling of coming home after a long day, something they took for granted then.",
                "Include a memory of small celebrations—birthdays, local festivals, or quiet gatherings—before trouble began.",
                "Have them reflect on a familiar sound from their old life—traffic, music, a kettle—now tied to bittersweet nostalgia.",
                "Include a moment where they think about a mundane goal they once had, like redecorating a room or learning a skill.",
                "Have them recall the unexpected comfort of predictable routines they never expected to miss.",
                "Include a reflection on how their old, uneventful life now feels like someone else’s story entirely.",
                "Have them recall a time when they believed people were fundamentally good, and how that belief quietly died.",
                "Include a moment where they reflect on their younger self with disbelief, wondering how they ever felt so hopeful.",
                "Have them remember an early moment when they first realized the world was harsher than they’d been taught.",
                "Include a reflection on a childhood belief or dream they once cherished, now feeling impossibly naïve.",
                "Have them describe the specific event that shattered their sense of safety or trust for the first time.",
                "Include a moment where they admit they used to see the world in simple terms—right and wrong—before everything got complicated.",
                "Have them recall a time when they trusted someone completely, only to be betrayed in a way they never forgot.",
                "Include a reflection on how their empathy has faded, tracing the slow erosion back to its earliest cracks.",
                "Have them describe the moment they realized the adults they admired were flawed, frightened, or corrupt.",
                "Include a memory of a place that once felt magical or comforting, now colored by bitterness or loss.",
                "Have them recall a promise they once made to themselves—one they broke long ago without noticing.",
                "Include a moment where they remember believing consequences were fair, before learning how arbitrary life can be.",
                "Have them reflect on a childhood fear that now seems trivial compared to the dangers they’ve survived.",
                "Include a memory of someone who tried to protect their innocence, and how they failed—or how the world overpowered them.",
                "Have them describe realizing that kindness could be exploited, and how that changed them forever.",
                "Include a moment where they face something they once found shocking but now accept with disturbing ease.",
                "Have them recall the first time they lied, stole, or harmed someone, and how strangely momentous it felt.",
                "Include a reflection on how their values shifted over time, slipping further from what they once believed was right.",
                "Have them acknowledge they can no longer remember the last moment they felt truly innocent.",
                "Include a moment where they question whether that innocence was ever real—or just a story they told themselves."
            };
            Random random = new Random();

            int count = 1 + random.Next(5);

            var selected = PromptOptions
                .OrderBy(x => random.Next())
                .Take(count);

            foreach (var prompt in selected)
            {
                BookPrompt += prompt + " ";
            }

            return BookPrompt;
        }


        public static string AddFlavourToLogMessage(string BookPrompt)
        {
            //Flavours that add variation between generations
            List<string> PromptOptions = new List<string>
            {
                "Hint that circumstances shifted gradually, leaving things where no one originally intended.",
                "Imply that small decisions accumulated over time, resulting in an unexpected outcome.",
                "Suggest that routines changed quietly, and no one paid attention until much later.",
                "Add a faint sense that something was overlooked for longer than anyone realized.",
                "Include the idea that past events left subtle traces that shaped where things ended up.",
                "Hint that certain actions were taken in haste, and their consequences lingered unnoticed.",
                "Suggest that people involved moved on before understanding what they had set in motion.",
                "Add a tone of uncertainty, as though no clear record of the chain of events exists.",
                "Imply that someone meant to follow up but never returned to finish the task.",
                "Introduce the notion that coincidences accumulated until they no longer felt random.",
                "Hint that the area had a reputation for holding things longer than intended.",
                "Suggest that processes meant to be temporary quietly became permanent.",
                "Add a subtle feeling that someone expected to tidy things up but never did.",
                "Present events as if reconstructed from fragments, none entirely reliable.",
                "Imply that several small miscommunications shaped the final outcome.",
                "Suggest that familiarity bred complacency, allowing things to slip through unnoticed.",
                "Introduce the possibility that old procedures were still running despite being forgotten.",
                "Hint that a minor oversight snowballed into a lasting situation.",
                "Add a subtle tone of inevitability, as though everything drifted toward this result.",
                "Suggest that the truth behind these events is simple but oddly difficult to pin down.",
                "Hint that people only speak about the situation in quiet tones, as if saying too much might draw attention.",
                "Suggest that no one knows the full story, only fragments passed between trusted ears.",
                "Add the sense that everyone involved insists they heard it from someone else first.",
                "Imply that the truth has been softened or twisted through retellings in backrooms and alley corners.",
                "Hint that some details were deliberately left unspoken, as if everyone agreed not to mention them.",
                "Suggest that those closest to the events avoid eye contact when the subject comes up.",
                "Add a tone that feels like gossip—uncertain, shifting, impossible to verify.",
                "Imply that what people claim to know doesn’t match what they’re willing to admit publicly.",
                "Hint that the story changes slightly every time it's repeated, as though shaped by fear or superstition.",
                "Suggest that certain names drop out of the conversation entirely, replaced with vague gestures.",
                "Add a sense that someone tried to bury the truth, but whispers kept it alive.",
                "Imply that disagreements over what happened are common, yet no one pushes too hard.",
                "Hint that some swear they saw something, while others claim it’s all exaggeration.",
                "Suggest the presence of details everyone pretends not to remember.",
                "Add the tone of a rumor that’s grown legs, wandering far beyond its origin.",
                "Imply that those involved hoped the story would fade, but quiet voices kept resurfacing it.",
                "Hint that anyone who knew too much learned to keep their opinions measured.",
                "Suggest that the earliest version of the tale has already been lost to speculation.",
                "Add a murmur of unease, as if the truth lies somewhere between fear and convenience."
            };
            Random random = new Random();

            int count = 1 + random.Next(1);

            var selected = PromptOptions
                .OrderBy(x => random.Next())
                .Take(count);

            foreach (var prompt in selected)
            {
                BookPrompt += prompt + " ";
            }

            return BookPrompt;
        }

        public static string GetQuestTheme()
        {
            Random random = new Random();
            List<string> questThemes = new List<string>()
            {
                "Corporate espionage thriller",
                "Frontier survival adventure",
                "Political conspiracy drama",
                "Underworld crime investigation",
                "Space-pirate hunting action",
                "High-tech infiltration stealth mission",
                "Frontier law enforcement procedural",
                "Scientific mystery exploration",
                "Interstellar noir detective case",
                "Post-war tension diplomacy scenario",
                "Cyberpunk corporate intrigue",
                "Cult infiltration psychological drama",
                "Resource-rush frontier scramble",
                "Black-market smuggling caper",
                "Megacorp sabotage operation",
                "Deep-space horror encounter",
                "Military rogue-unit pursuit",
                "Neon nightlife criminal underbelly story",
                "Lost-colony recovery expedition",
                "Derelict starship salvage thriller",
                "High-stakes data heist operation",
                "Freestar ranger borderlands pursuit",
                "UC black-ops containment mission",
                "Ancient alien artifact investigation",
                "Corporate whistleblower extraction",
                "Frontier homestead defense scenario",
                "Deep-cover pirate masquerade mission",
                "Smuggler network dismantling operation",
                "Grav-drive experimental test gone wrong",
                "Rogue AI containment emergency",
                "Volatile research site lockdown",
                "House Va'ruun zealot interception",
                "Trade Authority corruption scandal",
                "Undercover mercenary infiltration",
                "Disaster response and evacuation effort",
                "Outlaw biker-gang turf conflict (space variant)",
                "Terrormorph outbreak suppression",
                "Biohazard quarantine breach investigation",
                "Solar flare survival challenge",
                "Xenobiology specimen recovery mission",
                "Inter-corporate hostage negotiation",
                "Crimson Fleet double-cross mystery",
                "Long-range survey mission sabotage",
                "Contraband ring intelligence sweep",
                "Ancient ruins deep-dive expedition",
                "Corporate prototype theft recovery",
                "Weapons-testing black-site investigation",
                "Espionage sting in a luxury resort",
                "Orbital mining strike conflict",
                "Colony disappearance follow-up inquiry",
                "Mech parts smuggling crackdown",
                "Crew mutiny resolution scenario",
                "Ranger-led wilderness tracking operation",
                "Political prisoner rescue mission",
                "Secret military archive decryption quest",
                "Underbelly gang uprising response",
                "Off-grid commune infiltration",
                "Terraforming experiment failure investigation",
                "Illegal robotics production bust",
                "High-risk courier delivery under pursuit",
                "Medical crisis response on a remote outpost",
                "Corporate buyout sabotage drama",
                "Starship ghost-signal investigation",
                "False-flag operation exposure",
                "Undercover assignment in a hostile faction",
                "Freestar–UC cold war brinksmanship story",
                "Cybernetic augmentation trafficking probe",
                "Space station meltdown containment mission",
                "Unethical bio-experimentation operation",
                "Terrormorph gene-splicing conspiracy",
                "Illegal AI sentience creation program",
                "Organ harvesting black-site operation",
                "Mind-control neuroamp enhancement ring",
                "Forced labor exploitation network",
                "Corporate assassination contractor scheme",
                "Population surveillance and data theft project",
                "Weaponized xenofauna breeding initiative",
                "Grav-drive destabilization sabotage plot",
                "Forbidden cult indoctrination experiment",
                "Planetary resource theft and ecological ruin plot",
                "Starship hijacking and identity erasure program",
                "Dark-market cybernetic implantation racket",
                "Smuggled children indoctrination pipeline",
                "Atmospheric poisoning terraforming scam",
                "False-flag attack manufacturing project",
                "Memory-wiping psychological torture facility",
                "Space station plague-release plan",
                "Extinction-level prototype weapons testing scheme",
                "Fanatical ritual sacrifice operation",
                "Mind-breaking indoctrination compound",
                "Forbidden prophecy fulfillment scheme",
                "Brainwashing sermon-frequency experiment",
                "Cult-run abductee conversion program",
                "Star-serpent omens manipulation plot",
                "Ancient scripture forgery and control network",
                "Psychotropic-laced communion ritual ring",
                "False messiah resurrection project",
                "Doomsday astrological alignment plan",
                "Cult-led planetary cleansing doctrine",
                "Secret relic-worshipping assassination cell",
                "Faith-based hostage indoctrination pipeline",
                "Voices-of-the-Serpent transmission station",
                "Pilgrimage disappearance conspiracy",
                "Apocalyptic comet-summoning ritual attempt",
                "Cult-run excommunication death squad",
                "Unholy artifact corruption operation",
                "Deity-appeasement mass sacrifice trial",
                "Soul-harvesting theological experiment",
                "Hostage-taking ransom cartel",
                "Starship hijacking death squad",
                "System-wide extortion and protection racket",
                "Black-flag slave trading network",
                "Pirate-run organ harvesting ring",
                "Contraband warp-lane ambush operation",
                "Terrormorph egg smuggling conspiracy",
                "Deep-space civilian raiding campaign",
                "Corpse looting and identity theft ring",
                "Encrypted pirate broadcast intimidation channel",
                "Forced labor asteroid mine operation",
                "Grav-drive sabotage-for-hire scheme",
                "Black-market weapons augmentation lab",
                "Merciless bounty hunter entrapment plot",
                "Illicit starmap forgery and misdirection racket",
                "Pirate-led colony intimidation regime",
                "False distress beacon ambush plan",
                "Credit laundering through dead freighters",
                "Hostile takeover of frontier refueling stations",
                "Total-systems fear campaign for territory expansion",
                "Illegal cargo skimming ring",
                "Frontier trade lane robbery circuit",
                "Stolen ship parts reselling operation",
                "Unauthorized refueling siphon scheme",
                "Coercive debt collection crew",
                "Dockside intimidation and protection racket",
                "Asteroid miner shakedown network",
                "Counterfeit goods distribution racket",
                "Navigation beacon tampering scam",
                "Sabotage-for-hire starship repair grift",
                "Stolen medical supplies trafficking route",
                "Credit chip duplication workshop",
                "Pirate-run salvage fraud operation",
                "Extorted toll checkpoint in deep space",
                "Hijacked comm relay blackmail ring",
                "Undocumented passenger smuggling line",
                "Stolen fuel cell laundering scheme",
                "Illegal weapons resale market",
                "Freighter tracking and robbery planning hub",
                "Covert data theft and blackmail pipeline",
                "Local caravan ambush crew",
                "Frontier homestead raiding gang",
                "Small-time fuel siphoning ring",
                "Back-road toll extortion group",
                "Crop theft and livestock rustling outfit",
                "Abandoned mine squatters turned raiders",
                "Stolen tool and equipment resale scheme",
                "Frontier shuttle parts stripping crew",
                "Settlement well poisoning intimidation ploy",
                "Outpost burglary and stash-looting spree",
                "Travelers’ camp robbery circuit",
                "Local courier interception racket",
                "Blackmailing settlers for water rights",
                "Fence-operated stolen goods pipeline",
                "Illegal hunting and hide trafficking ring",
                "Derelict-ship scrap scavenger gang",
                "Unauthorized salvage claim jumpers",
                "Roadside distress-signal trap crew",
                "Wilderness tracker-mugger group",
                "Small-crew kidnap-for-ransom scheme",
                "Family-run homestead raiding ring",
                "Generational livestock rustling operation",
                "Water siphoning and rights intimidation scheme",
                "Multi-branch kinfolk burglary network",
                "Frontier land-claim squatting dynasty",
                "Backwoods moonshine smuggling line",
                "Illegal hunting grounds enforcement by family enforcers",
                "Credit chip counterfeiting in a farmhouse workshop",
                "Family-led toll checkpoint on remote trade roads",
                "Stolen farm equipment resale racket",
                "Clan-run abduction-for-ransom operation",
                "Rural cargo intercept crew using hidden trails",
                "Outlaw family feud spillover into settlement harassment",
                "Generational salvage-claim forgers",
                "Family-guarded contraband stash caves",
                "Rogue family militia pressuring nearby settlers",
                "Unmarked grave cleanup after ambush operations",
                "Clan-run courier sabotage and package theft",
                "Blackmail through captured family records of locals",
                "Family-operated frontier intimidation patrols",
                "Rural sabotage cell targeting corporate pipelines",
                "Frontier rebels dismantling automated farm drones",
                "Underground movement stealing back overtaxed harvests",
                "Rebel group disabling corporate survey outposts",
                "Family-led strike force attacking land-grab teams",
                "Confiscated corporate equipment redistribution network",
                "Rebel sabotage of automated factory shipments",
                "Backwoods encryption hub leaking internal corporate memos",
                "Rural activists blocking new corporate mining claims",
                "Outlaw family raiding supply convoys feeding corporate expansion",
                "Rebel hackers disrupting corporate water ration controls",
                "Frontier militia resisting forced property buyouts",
                "Clandestine crop-sharing network dodging corporate quotas",
                "Rural ambush crew targeting exploitative contract enforcers",
                "Dissenting settlers hijacking drone patrol routes",
                "Rebel demolition team targeting unapproved corp installations",
                "Family-led resistance distributing banned farming tools",
                "Sabotage squad contaminating corp-exclusive resource caches",
                "Rebel scouts tracking illegal corporate wildlife culls",
                "Underground alliance sheltering settlers evading corp debt collectors"
            };
            var theme = questThemes[random.Next(questThemes.Count)];
            Console.WriteLine(theme);
            return theme;
        }


        public static string AddReportTypes(string BookPrompt)
        {
            //Flavours that add variation between generations
            List<string> PromptOptions = new List<string>
            {
                "Two short paragraphs.",
                "A three-section mini-dossier (Background, Activities, Notes).",
                "A short bullet-point intelligence summary.",
                "A compact internal memo (3 to 5 sentences).",
                "A field agent observation report.",
                "A brief narrative overview written like an incident recap.",
                "A senior analyst incident summary.",
                "An internal security briefing note.",
                "A condensed behavioral risk profile.",
                "A frontline investigator situation recap.",
                "A regional operations intelligence note.",
                "A covert surveillance extract.",
                "A rapid assessment threat outline.",
                "A personnel history compression file.",
                "A classified misconduct review.",
                "A compressed target bio entry.",
                "A threat evaluation card summarizing key risk factors.",
                "A compact operational timeline with inferred motivations.",
                "A three-bullet persona snapshot (Behavior, Skills, Weaknesses).",
                "A short-form criminal pattern analysis.",
                "A restricted-access case synopsis prepared for leadership.",
                "A tactical engagement pre-brief summarizing known intel.",
                "A decrypted message reconstruction compiled from fragments.",
                "A psychological micro-profile highlighting instability markers.",
                "A short incident banner summarizing who, what, and why.",
                "A rapid context sheet used for briefing field operatives.",
                "A UC Vanguard tactical précis outlining mission-relevant behavioral markers.",
                "A Freestar Collective ranger’s condensed frontier case note.",
                "A Ryujin Industries efficiency-audit snapshot detailing actionable intel.",
                "A Crimson Fleet codex blurb compiled from black-market chatter.",
                "A Trade Authority dispute summary focused on illicit asset movements.",
                "A Va’ruun scripture-tinged omen analysis interpreting the target’s actions.",
                "A Settled Systems spacer-rumor digest reconstructed from dockside whispers.",
                "A Xenowardens ecological interference note linking the target to regional disruption.",
                "A decrypted UC SysDef intercept annotated with operational significance."
            };
            Random random = new Random();

            int count = 1 + random.Next(5);

            var selected = PromptOptions
                .OrderBy(x => random.Next())
                .Take(count);

            foreach (var prompt in selected)
            {
                BookPrompt += prompt + " ";
            }

            return BookPrompt;
        }
    }
}
