using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace FrankyCLI.questgen_tools
{
    public class PromptFlavourTools
    {
        public static string AddFlavourToShipBook(string BookPrompt)
        {
            //Flavours that add variation between generations
            List<string> PromptOptions = new List<string>
            {
                "Include hints of romantic tension—unspoken crushes, forbidden relationships, jealousy, or awkward encounters.",
                "Mention a scandalous rumor circulating aboard the ship and how they personally feel about the people involved.",
                "Include vivid details about their daily life on the ship, their private thoughts, and how they feel about recent events.",
                "Incorporate flavorful gossip or rumors they’ve heard about other people encountered during their travels.",
                "Describe sensory details of life aboard the ship—smells, sounds, cramped quarters, rituals.",
                "Reveal an internal conflict or personal dilemma they are struggling with, showing how it shapes their decisions and mood.",
                "Describe their relationships with specific crew members—alliances, grudges, secrets, or unspoken tensions.",
                "Let their cultural background, upbringing, or past experiences influence how they interpret events and express themselves.",
                "Give their writing a distinctive verbal style—slang, metaphors, pacing, or quirks that reflect who they are.",
                "Have them reflect on a recent incident aboard the ship or during their travels, revealing how it affected them personally.",
                "Include subtle hints of unease, suspicion, or foreshadowing about something they believe is about to happen.",
                "Allow moments of honest vulnerability—fears, regrets, insecurities—that they would only admit in a private diary.",
                "Add small worldbuilding details such as customs, slang, ship traditions, or local myths they’ve encountered.",
                "Include mentions of their personal goals, ambitions, or hidden desires, and how the journey affects their pursuit of them.",
                "Describe how the environment affects them physically—fatigue from long shifts, discomfort from ship movement, or reactions to alien climates.",
                "Suggest that someone aboard the ship might be sabotaging others, spreading lies, or hiding a betrayal.",
                "Describe any power struggles, favoritism, or political maneuvering happening within the crew ranks.",
                "Include a moment where someone had an emotional outburst—anger, tears, panic—and explain the fallout.",
                "Highlight social tensions between crew factions, cliques, or individuals who simply can’t stand each other.",
                "Show how misunderstandings or half-heard conversations have sparked distrust or paranoia among the crew.",
                "Include petty rivalries—competition over duties, attention, rank, or even trivial things like cabin space.",
                "Have them reveal a secret they overheard or discovered accidentally—something they know could cause trouble if exposed.",
                "Include an awkward or embarrassing interaction with someone they’re attracted to, and their overthinking afterward.",
                "Have them struggle with unrequited love or uncertainty about whether their feelings are returned.",
                "Let memories of a past lover influence how they view new relationships or romantic opportunities.",
                "Hint at secret late-night conversations or hidden rendezvous away from prying eyes on the ship.",
                "Capture their emotional confusion—torn between desire, duty, fear, or loyalty—regarding someone they care for.",
                "Have them reflect on a strained or complicated relationship with a parent and how it affects their choices today.",
                "Mention ongoing or unresolved rivalry with a sibling—competition, bitterness, or jealousy that still lingers.",
                "Describe the pressure of family expectations weighing on them and their fear of disappointing those back home.",
                "Include memories of arguments or ideological clashes with older family members that shaped their worldview.",
                "Have them hint at a dark or embarrassing family secret they fear others might discover.",
                "Describe an estranged family member they haven’t spoken to in years, along with guilt or resentment about the silence.",
                "Include the burden of inheriting a family legacy—duties, debts, curses, or a name they struggle to live up to.",
                "Show their anxiety about family members far away—illness, danger, conflict—and their helplessness being unable to assist.",
                "Have them react to receiving unexpected family news—a letter, rumor, or message—that stirs old wounds.",
                "Have them describe the everyday chores or repetitive tasks they performed today and how tedious or oddly satisfying they found them.",
                "Include small annoyances—misplaced tools, squeaky doors, lukewarm meals, or a crew member’s irritating habits.",
                "Have them comment on the day’s weather or ship conditions and how it subtly influenced their mood.",
                "Mention simple, routine interactions—brief conversations, polite nods, shared meals—that give a sense of normalcy.",
                "Describe mundane self-care: cleaning clothes, patching gear, trimming hair, or trying to get some decent sleep.",
                "Have them note what they ate or drank today, how it tasted, and any small pleasures or disappointments.",
                "Have them describe a personal or family tradition they try to uphold even while far from home, and how it comforts them.",
                "Include a memory of a cultural ritual or celebration they miss, reflecting on how different it feels to be away during that time.",
                "Have them participate in a small shipboard tradition—old, improvised, or silly—and note how it strengthens crew camaraderie.",
                "Describe a tradition unique to their homeland, and how others react when they explain or attempt to recreate it.",
                "Include a moment where they break a long-standing tradition, willingly or not, and wrestle with the guilt or freedom that follows.",
                "Have them reflect on a tradition they once disliked but now cherish, realizing how much it shaped their identity.",
                "Describe them teaching someone else a tradition, passing down knowledge that feels fragile but important to preserve.",
                "Include a reflection on a tradition that has changed over time, and their struggle to accept or reject this new version of it.",
                "Have them question whether certain traditions still serve a purpose, or if they continue only out of habit or pressure.",
                "Describe a newly emerging tradition aboard the ship, something small but meaningful that helps the crew feel like a family.",
                "Include minor logistical tasks—inventory checks, paperwork, reorganizing supplies, running slow errands around the ship.",
                "Have them describe cleaning or organizing their bunk space, noting small frustrations or tiny comforts they discovered.",
                "Include a mention of them waiting in a long line—mess hall, supply depot, or wash station—and their thoughts while idling.",
                "Describe them dealing with a mildly broken item—stuck locker, jammed drawer, loose hinge—and their attempt to fix or ignore it.",
                "Have them comment on doing basic personal grooming—trimming nails, combing hair, or cleaning boots—and how oddly calming or boring it felt.",
                "Include a moment where they search for a misplaced everyday item and grumble about how often this seems to happen.",
                "Describe them washing or mending a piece of clothing, noticing stains, tears, or smells picked up during the day.",
                "Have them note the repetitive sounds around them—dripping pipes, humming engines, footsteps in the corridor—and how they blend into routine life.",
                "Include a short reflection on a dull shift where nothing noteworthy happened, yet they found themselves daydreaming anyway.",
                "Mention a simple shared meal with the crew, focusing on the plain food, casual chatter, and comfortable ordinariness of it.",
                "Have them question whether they are becoming the person they once hoped to be, revealing doubts or pride in their growth.",
                "Include a moment where they analyze their recent decisions, wondering if they acted out of fear, desire, or obligation.",
                "Have them reflect on a personal flaw they’ve noticed—impatience, jealousy, pride—and how it affects their relationships.",
                "Describe them contemplating a past mistake that still haunts them, and what they would do differently if given the chance.",
                "Include a reflection on what they truly value—loyalty, freedom, safety, adventure—and how the journey tests those beliefs.",
                "Have them assess their emotional state, noting what has changed within them over time and what remains stubbornly the same.",
                "Include thoughts about whether they deserve the good or bad things happening around them, revealing guilt or gratitude.",
                "Have them compare who they were before the voyage to who they are now, acknowledging subtle or dramatic shifts in identity.",
                "Describe them wrestling with uncertainty about their future, questioning where they belong and what purpose they serve.",
                "Have them reflect on a moment of unexpected joy, comfort, or peace, and how rare or precious such moments feel to them.",
                "Have them recognize a small moment of peace or comfort that made them feel like they’re finally beginning to heal.",
                "Include a reflection on someone who has recently helped them emotionally, even in ways they didn’t expect.",
                "Describe them forgiving themselves for a past mistake, or at least taking the first uncertain steps toward forgiveness.",
                "Have them acknowledge progress they’ve made—subtle changes in how they react, think, or cope compared to before.",
                "Include a moment where they let go of something they’ve been clinging to—anger, guilt, fear—and feel lighter for it.",
                "Have them realize they no longer feel as alone as they once did, thanks to new bonds or gentle kindness from others.",
                "Describe them embracing vulnerability, allowing themselves to feel sadness or hope without judgment.",
                "Have them reflect on advice someone gave them, recognizing that it brought clarity or comfort when they needed it most.",
                "Include a realization that they deserve happiness or healing, even if accepting that truth still feels strange.",
                "Have them acknowledge that healing does not mean forgetting, and that some wounds still ache even as they begin to close.",
                "Include a moment where they accept a painful truth about themselves, realizing that facing it is the only way forward.",
                "Describe them confronting a memory they’ve avoided, letting it hurt so it can finally lose some of its power over them.",
                "Have them realize that some relationships cannot be repaired, and the grief of that acceptance becomes part of their healing.",
                "Include a reflection on how suffering has reshaped them, leaving marks they may never erase but can learn to live with.",
                "Have them find strength in surviving something that once broke them, even if the pride feels uncomfortable or undeserved.",
                "Describe them letting go of a hope that has long tormented them, finding grim relief in finally releasing it.",
                "Have them face the consequences of their own actions, accepting responsibility as a painful but necessary step toward growth.",
                "Include a moment where they recognize that healing sometimes feels like numbness, and wonder if that’s progress or simply survival.",
                "Have them admit that they are still angry or afraid, but that these emotions no longer rule them the way they once did.",
                "Have them notice a small habit or ritual that has quietly helped them cope—journaling, breathing, watching the stars—and how it soothes them.",
                "Describe them getting briefly annoyed or amused by something trivial, such as a crewmate’s loud chewing or mismatched socks."
            };
            Random random = new Random();

            int count = 1 + random.Next(5);

            var selected = PromptOptions
                .OrderBy(x => random.Next())
                .Take(count);

            foreach (var prompt in selected)
            {
                BookPrompt += prompt + " ";
            }

            return BookPrompt;
        }

        public static string AddFlavourToTargetBook(string BookPrompt)
        {
            //Flavours that add variation between generations
            List<string> PromptOptions = new List<string>
            {
                "Include hints of romantic tension—unspoken crushes, forbidden relationships, jealousy, or awkward encounters.",
                "Include a moment where they recognize that healing sometimes feels like numbness, and wonder if that’s progress or simply survival.",
                "Include a moment where they admit they can no longer tell who they can trust, convinced someone close is plotting against them.",
                "Have them describe hearing whispers or movements they can’t explain, certain someone is watching from the shadows.",
                "Include a reflection on documents or messages they found that don’t add up, leading them to suspect a hidden conspiracy.",
                "Have them express fear that their communications are being intercepted, forcing them to write cautiously or cryptically.",
                "Include a moment where they second-guess an ally’s kindness, wondering if it’s genuine or a calculated trap.",
                "Have them obsess over patterns—footsteps, schedules, odd glances—convinced these small signs reveal a threat.",
                "Include a mention of sleepless nights where every creak or rustle feels like someone approaching them.",
                "Have them question whether their enemies are already within their circle, hiding behind familiar faces while plotting.",
                "Include a fleeting thought that even their own memories might be altered or unreliable, leaving them unsure what is real.",
                "Have them describe the growing certainty that someone is always one step ahead of them, anticipating their every move.",
                "Have them confess that their personal relationships are falling apart faster than they can hold them together.",
                "Have them justify their actions as necessary, insisting no one else had the courage to do what they did.",
                "Include a moment where they argue that the world forced their hand, leaving them no choice but to act as they have.",
                "Have them claim that everyone judging them would have done the same in their situation—if they were honest.",
                "Include a reflection where they paint themselves as a misunderstood hero rather than a villain.",
                "Have them insist that their so-called crimes were actually acts of survival, not malice.",
                "Include a moment where they blame others for pushing them to extremes, absolving themselves of responsibility.",
                "Have them argue that their victims were complicit in their own downfall, one way or another.",
                "Include a justification that rules and laws are tools of the weak, and they refuse to be limited by them.",
                "Have them reframe their betrayals as strategic necessities rather than moral failings.",
                "Include a moment where they claim the ends always justify the means—especially when they are the one deciding the ends.",
                "Have them insist that anyone who opposes them simply doesn’t understand their brilliance or vision.",
                "Include a reflection where they portray themselves as the only one capable of making the hard decisions.",
                "Have them accuse others of hypocrisy, claiming they’re merely more honest about doing what needs to be done.",
                "Include a moment where they rewrite past events to cast themselves as the victim of unfair judgment.",
                "Have them justify cruelty as discipline, claiming it forges stronger people around them.",
                "Include a moment where they argue that mercy would have caused more harm than their harsh choices.",
                "Have them claim that fate or destiny chose them, and therefore their actions are beyond ordinary morality.",
                "Include a justification that power naturally belongs to those willing to seize it.",
                "Have them insist that their enemies brought their fate upon themselves by standing in the way.",
                "Include a reflection where they convince themselves that those they hurt were obstacles, not people.",
                "Have them reinterpret betrayal as liberation—freeing others from their own misguided paths.",
                "Include a moment where they claim that if they hadn’t acted, someone worse would have.",
                "Have them assert that their intelligence places them above conventional ethical constraints.",
                "Include a justification that loyalty is overrated, and only results truly matter.",
                "Have them insist that anyone calling them dangerous simply fears what they don’t understand.",
                "Include a moment where they frame manipulation as guidance, claiming others needed their direction.",
                "Have them argue that their selfishness is actually a form of clarity others lack.",
                "Include a reflection where they celebrate their ruthlessness as a virtue in a broken world.",
                "Have them claim that regret is pointless because every choice they made was the correct one.",
                "Include a moment where they confidently declare that history will vindicate them, even if no one else will.",
                "Have them describe how their morals have slowly eroded, and how disturbingly easy it has become to cross new lines.",
                "Include a moment where they feel a thrill from doing something they once believed was wrong, recognizing how far they've fallen.",
                "Have them admit that harming others no longer bothers them the way it used to, and wonder when that shift happened.",
                "Include a reflection where they take pride in manipulation or cruelty, seeing it as a sign of strength rather than decay.",
                "Have them justify exploiting the vulnerable, claiming that weakness exists to be used.",
                "Include a moment where they recognize the person they used to be—and feel nothing but contempt for that version of themselves.",
                "Have them describe ignoring their conscience so many times that it eventually stopped speaking to them.",
                "Include a reflection where they acknowledge they now measure right and wrong by convenience rather than principle.",
                "Have them recount a moment when they enjoyed watching someone suffer, realizing they no longer pretend to care.",
                "Include a moment where they see someone else’s morality as naive and mock them for it, openly or internally.",
                "Have them admit they’ve grown addicted to power, control, or fear, and feel hollow without it.",
                "Include a description of how they've started treating people as tools or obstacles rather than human beings.",
                "Have them realize they crossed a moral line long ago—and now keep running just to avoid facing it.",
                "Include a moment where they twist morality into a weapon, using it only when it benefits them.",
                "Have them confess that corruption was not a fall, but a choice they embraced willingly.",
                "Include a reflection where they measure their worth by how effectively they can break or bend others.",
                "Have them describe how guilt has faded into numbness, leaving them free to act without hesitation.",
                "Include a moment where they look at an innocent person and feel nothing but opportunity.",
                "Have them acknowledge that they now fear redemption—not because it seems impossible, but because they no longer want it.",
                "Include a moment where they catch themselves savoring the thought of crossing an even darker line next.",
                "Have them describe a moment where they inflicted pain simply to see how someone would react, and felt a cold satisfaction.",
                "Include a reflection where they admit they’ve grown curious about how far they can push someone before they break.",
                "Have them recount a time they watched someone suffer and chose not to intervene, savoring the power it gave them.",
                "Include a moment where they justify their cruelty as a lesson others needed to learn.",
                "Have them describe enjoying the fear in someone’s eyes, recognizing it as proof of their control.",
                "Include a reflection where they admit hurting others has become easier—almost routine.",
                "Have them recall a moment when someone begged for mercy, and how denying it made them feel powerful.",
                "Include a moment where they test how much cruelty they can disguise as necessity.",
                "Have them describe harming someone not out of anger or strategy, but pure curiosity.",
                "Include a reflection where they acknowledge they could have been kind, and deliberately chose not to be.",
                "Have them recount a situation where they exploited someone's vulnerability with calculated precision.",
                "Include a moment where they mock someone’s pain, seeing it as weakness rather than something to empathize with.",
                "Have them describe taking pleasure in ruining someone’s hopes or plans, just to watch their reaction.",
                "Include a reflection where they recognize that others fear them—and secretly enjoy that fear.",
                "Have them recount deliberately manipulating someone into harming themselves emotionally or physically.",
                "Include a moment where they admit cruelty has become a habit, something they perform without thinking.",
                "Have them describe feeling bored when people obey, craving the challenge of breaking those who resist.",
                "Include a reflection where they enjoy withholding something—information, help, comfort—just to watch someone struggle.",
                "Have them recount a moment where they escalated conflict intentionally, savoring the chaos it caused.",
                "Include a moment where they acknowledge that kindness feels foreign now, replaced entirely by sharp, predatory instincts.",
                "Have them cite philosophical ideas to justify their actions, convincing themselves that morality is subjective anyway.",
                "Include a moment where they claim that human behavior is driven by instinct, freeing themselves from responsibility.",
                "Have them reflect on the idea that suffering builds character, using it to excuse what they’ve done to others.",
                "Include a justification that people create their own misery, and they merely accelerate the inevitable.",
                "Have them use psychological theories to explain away their cruelty as a natural coping mechanism.",
                "Include a moment where they reinterpret their selfishness as healthy self-preservation, grounded in ‘rational’ thinking.",
                "Have them claim that empathy is a social construct and that freeing themselves from it brings clarity.",
                "Include a reflection where they argue that purpose and meaning are illusions, making any action permissible.",
                "Have them twist philosophical teachings into excuses for manipulation or betrayal.",
                "Include a moment where they insist that everyone is ruled by unconscious impulses, so blaming themselves is pointless.",
                "Have them justify their actions through a belief in determinism, insisting they had no real choice anyway.",
                "Include a reflection where they adopt a nihilistic worldview to distance themselves from guilt or consequences.",
                "Have them use armchair psychology to diagnose others’ flaws, avoiding scrutiny of their own behavior.",
                "Include a moment where they claim that morality evolves, and they’re simply ahead of everyone else ethically.",
                "Have them convince themselves they are conducting ‘experiments’ on human nature rather than harming people.",
                "Include a reflection where they argue that emotional detachment is a sign of enlightenment rather than decay.",
                "Have them justify manipulation as a form of guiding others toward their ‘true potential.’",
                "Include a moment where they use philosophical paradoxes to muddy their own sense of right and wrong.",
                "Have them claim that guilt is merely a conditioned response, one they have successfully outgrown.",
                "Include a reflection where they reframe their darkest impulses as authenticity—being true to their ‘real self.’",
                "Include a moment where they realize they’ve pushed someone important away without meaning to, and now regret it deeply.",
                "Have them describe how constant stress is making them lash out at people they care about, even when they don’t want to.",
                "Include a reflection on how their old routines, comforts, or joys no longer feel like they belong to them.",
                "Have them admit they no longer recognize the person they’re becoming, and fear it’s too late to turn back.",
                "Include a moment where they try to contact someone they love, only to realize they have no idea what to say anymore.",
                "Have them describe the painful moment they understood a relationship they valued has quietly died over time.",
                "Include a realization that their work, choices, or obsessions have consumed everything else in their life.",
                "Have them hide their guilt behind lofty quotes or theories, hoping complex words will distract from simple wrongdoing.",
                "Include a moment where they speak in grand academic tones to make their actions sound profound rather than cruel.",
                "Have them overanalyze trivial details to appear intelligent, avoiding the emotional truth beneath their behavior.",
                "Include a reflection where they bury remorse under layers of abstract reasoning, pretending depth where none exists.",
                "Have them use obscure terminology to make others doubt whether they even understand the situation well enough to blame them.",
                "Include a moment where they frame their harmful choices as part of a ‘greater intellectual framework,’ masking their insecurity.",
                "Have them pretend to be above ordinary morality by referencing philosophers they barely understand.",
                "Include a reflection where they nitpick semantics to avoid admitting fault, turning guilt into a debate instead of a confession.",
                "Have them insist that only the ‘enlightened’ can comprehend their motives, using pretension to dodge accountability.",
                "Include a moment where they drown their conscience in pedantic arguments, hoping complexity will smother the truth.",
                "Have them confess they’ve been hiding their struggles from everyone, terrified that vulnerability will break what little they have left.",
                "Include a moment where they reflect on how loneliness crept in slowly, until it became the only constant in their life.",
                "Have them reminisce about the simple routines they once had—morning habits, favorite foods, or quiet hobbies.",
                "Include a moment where they recall a job they used to do, unremarkable but steady, and how different life felt then.",
                "Have them describe a familiar street, shop, or café they visited regularly before everything changed.",
                "Include a reflection on an old friend or coworker they lost touch with long before turning to crime.",
                "Have them recall the mundane frustrations of their old life—long lines, broken appliances, nosy neighbors.",
                "Include a moment where they remember saving up for small purchases, appreciating every coin.",
                "Have them describe a favorite place they used to relax, simple and ordinary, now impossibly distant.",
                "Include a memory of chores or tasks they used to complain about, now seeming strangely comforting in hindsight.",
                "Have them recall a hobby they once practiced—gardening, tinkering, reading—that grounded them.",
                "Include a moment where they reflect on old clothes, tools, or belongings they left behind without meaning to.",
                "Have them describe a daily commute they once found boring, now almost nostalgic in its predictability.",
                "Include a memory of cooking simple meals or sharing them with someone before their life unraveled.",
                "Have them recall an ordinary responsibility they had—taking care of a pet, paying bills, fixing leaks.",
                "Include a moment where they remember casual conversations with neighbors or acquaintances they barely knew.",
                "Have them describe the feeling of coming home after a long day, something they took for granted then.",
                "Include a memory of small celebrations—birthdays, local festivals, or quiet gatherings—before trouble began.",
                "Have them reflect on a familiar sound from their old life—traffic, music, a kettle—now tied to bittersweet nostalgia.",
                "Include a moment where they think about a mundane goal they once had, like redecorating a room or learning a skill.",
                "Have them recall the unexpected comfort of predictable routines they never expected to miss.",
                "Include a reflection on how their old, uneventful life now feels like someone else’s story entirely.",
                "Have them recall a time when they believed people were fundamentally good, and how that belief quietly died.",
                "Include a moment where they reflect on their younger self with disbelief, wondering how they ever felt so hopeful.",
                "Have them remember an early moment when they first realized the world was harsher than they’d been taught.",
                "Include a reflection on a childhood belief or dream they once cherished, now feeling impossibly naïve.",
                "Have them describe the specific event that shattered their sense of safety or trust for the first time.",
                "Include a moment where they admit they used to see the world in simple terms—right and wrong—before everything got complicated.",
                "Have them recall a time when they trusted someone completely, only to be betrayed in a way they never forgot.",
                "Include a reflection on how their empathy has faded, tracing the slow erosion back to its earliest cracks.",
                "Have them describe the moment they realized the adults they admired were flawed, frightened, or corrupt.",
                "Include a memory of a place that once felt magical or comforting, now colored by bitterness or loss.",
                "Have them recall a promise they once made to themselves—one they broke long ago without noticing.",
                "Include a moment where they remember believing consequences were fair, before learning how arbitrary life can be.",
                "Have them reflect on a childhood fear that now seems trivial compared to the dangers they’ve survived.",
                "Include a memory of someone who tried to protect their innocence, and how they failed—or how the world overpowered them.",
                "Have them describe realizing that kindness could be exploited, and how that changed them forever.",
                "Include a moment where they face something they once found shocking but now accept with disturbing ease.",
                "Have them recall the first time they lied, stole, or harmed someone, and how strangely momentous it felt.",
                "Include a reflection on how their values shifted over time, slipping further from what they once believed was right.",
                "Have them acknowledge they can no longer remember the last moment they felt truly innocent.",
                "Include a moment where they question whether that innocence was ever real—or just a story they told themselves."
            };
            Random random = new Random();

            int count = 1 + random.Next(5);

            var selected = PromptOptions
                .OrderBy(x => random.Next())
                .Take(count);

            foreach (var prompt in selected)
            {
                BookPrompt += prompt + " ";
            }

            return BookPrompt;
        }


        public static string AddFlavourToLogMessage(string BookPrompt)
        {
            //Flavours that add variation between generations
            List<string> PromptOptions = new List<string>
            {
                "Retell the events in a gritty noir tone—cynical, shadowed, and heavy with unspoken suspicions.",
                "Rewrite the summary using clipped, precise military language, as if logged in an after-action report.",
                "Present the events as a sanitized corporate memo full of jargon, euphemisms, and liability management.",
                "Retell the facts with the voice of a conspiracy theorist, layering implication and paranoia without altering the truth.",
                "Frame the events like an academic analysis, detached and scholarly, as though pieced together years later.",
                "Style the summary as if reconstructed from fragmented personal logs, lending a human, emotional undertone.",
                "Present the account in the tone of spacer folklore—mythic, exaggerated, and retold around mess-hall tables.",
                "Rewrite the summary like a breaking news broadcast—urgent, dramatic, and slightly sensational.",
                "Frame the events in sterile forensic language, focusing on evidence trails and procedural breakdowns.",
                "Add a layer of dark humor or grim irony, highlighting tragic timing without changing the facts.",
                "Retell the events with the sweeping, dramatic tone of a tragic epic—grand, solemn, and poetic.",
                "Frame the summary as a heavily redacted government document, with '[REDACTED]' segments for dramatic effect.",
                "Rewrite the account from the perspective of an AI analysis—cold, clinical, and emotionless.",
                "Present the events like an investigative news deep-dive, connecting implications and systemic failures.",
                "Use a somber, reflective tone as if written by a historian chronicling a forgotten tragedy.",
                "Retell the facts in the voice of frontier tall tales—bold, exaggerated, and rugged.",
                "Frame the events like a legal deposition—stilted, defensive, overly formal, but accurate.",
                "Rewrite the summary as if pieced together from emergency alerts or partial distress transmissions.",
                "Use a tone focused strictly on financial and logistical impact, as though written by a corporate auditor.",
                "Present the summary in a melancholic, elegiac voice, mourning the loss and contemplating its meaning.",
                "Add a small sensory detail—sounds, smells, or environmental cues—that reinforces the existing events.",
                "Include a brief mention of the crew’s last routine activity before the incident, keeping it consistent with the facts.",
                "Add a minor detail about equipment, cargo, or tools that were present, supporting the established narrative.",
                "Include a short note about the lighting, atmosphere, or condition of the corridors to enhance immersion.",
                "Add a small clue recovered from the scene—scuffed floors, scattered items, or half-finished tasks.",
                "Include a small observation about the target’s personal effects that survived the event.",
                "Add a brief detail about the state of the navigation systems or consoles at the time of discovery.",
                "Include hints of environmental decay—frosted panels, drifting debris, or faint residue from the chem leak.",
                "Add a minor timestamp or sequence detail to emphasize the rushed or chaotic nature of events.",
                "Include a detail about a forgotten datapad entry, half-saved file, or corrupted message supporting the known outcome.",
                "Add a short mention of background chatter or logs that stop abruptly as the disaster unfolds.",
                "Include a faint trace of the chemicals involved—color, vapor residue, or corrosion marks.",
                "Add a detail about the power state—flickering lights, drained batteries, or backup systems failing.",
                "Include a note on temperature changes caused by the incident—heat spikes, cold pockets, or uneven airflow.",
                "Add a minor clue left by a crew member—an open locker, a dropped tool, or a half-worn uniform tag.",
                "Include a description of how certain systems auto-reacted—sealed bulkheads, alarms, or emergency vents.",
                "Add a subtle indication of the crew’s last movements—footprints, fingerprints, or partially completed tasks.",
                "Include a small environmental oddity that matches the established chemical rupture—warped metal, pitted surfaces, or discoloration.",
                "Add a fleeting detail about how the vessel or location appears when first boarded—dust motes, drifting papers, dim console glow.",
                "Include a final subtle detail pointing to the consequences—oxidation marks, frozen displays, or stale, recycled air frozen in time.",
                "Provide a concise account of a routine job that spiraled into something far more complicated than expected.",
                "Summarize an incident involving corporate negligence or smuggling gone wrong, framed with calm, investigative detachment.",
                "Describe a derelict vessel or abandoned outpost with a hint of mystery tied to missing logs or corrupted data streams.",
                "Mention a faction connection—Freestar, UC, Crimson Fleet—without overstating their involvement.",
                "Include a technical failure or anomaly that sets the stage, such as compromised life support or corrupted navigation layers.",
                "Introduce a deceased or missing crew whose final moments are pieced together through scattered system logs.",
                "Frame the objective around retrieving a key data slate, encrypted file, or malfunctioning module tied to the event.",
                "Hint at rival interests or unknown third parties who may have benefited from the disaster.",
                "Add a detail about environmental hazards—pressure leaks, toxic vapor, or unstable gravity fields.",
                "Include a subtle tone of procedural investigation, as if uncovering the truth is just another day’s work.",
                "Describe the remains of a botched operation with quiet, factual resignation rather than drama.",
                "Reference a hidden route, contraband manifest, or unauthorized detour that explains how the situation unraveled.",
                "Include a brief line acknowledging that the crew’s final decisions were rushed, desperate, or poorly calculated.",
                "Frame the incident as one small part of a much larger pattern across the settled systems.",
                "Note that automated systems attempted to compensate but ultimately failed, locking in the tragic outcome.",
                "Add a detail suggesting the player will be combing through whatever the target left behind—logs, caches, or hardware.",
                "Describe the scene as eerily quiet, with only dormant systems or faint alarms offering clues to what happened.",
                "Include a hint that the recovered evidence may reshape the understanding of the mission’s true purpose.",
                "Reference a chain of events triggered by greed, miscalculation, or sheer bad luck, delivered with understated tone.",
                "Present the situation as an opportunity to uncover the truth, secure valuable intel, or tie off a loose end long forgotten.",
                "Add a detail about the condition of the equipment involved—scuffed panels, scorched wiring, or residue from prior use.",
                "Include a mention of a specific tool or device left behind, hinting at the crew’s last attempt to fix the problem.",
                "Describe the cargo containers with a small visual cue—dented frames, cracked seals, or flickering status lights.",
                "Add a detail about the manifest tags or shipping labels, showing signs of hasty alterations or forged entries.",
                "Include a brief note about a data slate or terminal with half-finished commands still visible on-screen.",
                "Mention minor wear on structural supports or bulkheads, suggesting the crew had been ignoring needed maintenance.",
                "Add a subtle observation about the chem canisters—unusual coloring, warped metal, or faint particulate trails.",
                "Include a detail about the navigation readout—ghost entries, corrupted overlays, or mismatched coordinates.",
                "Describe a scattered personal item—an ID badge, a torn glove, or a dropped toolkit—as a silent clue.",
                "Add a detail about environmental indicators—pressure gauges stuck mid-range or CO₂ alarms blinking idle warnings.",
                "Include a small malfunction in an auxiliary system—unresponsive buttons, intermittent power cycling, or jammed shutters.",
                "Mention the condition of emergency gear—discarded masks, half-open med packs, or offline hazard suits.",
                "Add a clue from the internal lighting—burned-out strips, emergency red glow, or low-power pulsing.",
                "Include faint markings on the floor—drag streaks, chemical stains, or footprints frozen mid-action.",
                "Describe the status of security systems—passive turrets in sleep mode, disabled cameras, or overridden locks.",
                "Add a detail about an overlooked storage crate—loose hinges, broken seal, or mislabeled contents.",
                "Include a quick note about atmospheric sensors flickering between normal and contaminated readings.",
                "Mention the state of comms equipment—signal boosters humming, cracked headsets, or fragmented audio logs.",
                "Add a subtle detail about shipboard robotics—maintenance drones frozen mid-task or tools still extended.",
                "Include a detail about dataport connectors—sparking edges, melted casing, or improvised bypass clips.",
                "Include a faint detail about scuffed floor panels or drag marks hinting at the crew’s final movements.",
                "Add a mention of scattered tools or debris arranged in a way that suggests a rushed attempt at repairs.",
                "Describe a flickering light source casting uneven shadows that make the scene feel frozen in the moment of disaster.",
                "Include a detail about a half-eaten meal or abandoned drink, emphasizing how abruptly events unfolded.",
                "Add a note about handprints, smudges, or fingerprints on surfaces, showing where the crew tried to brace themselves.",
                "Mention an open maintenance hatch or exposed wiring that implies a desperate improvisation.",
                "Include signs of environmental decay—condensation streaks, rust blooms, or frozen vapor residue.",
                "Describe a chair knocked over or a stool lying on its side, hinting at chaos moments before the end.",
                "Add a detail about personal effects left behind—photos, trinkets, or logs—scattered across a workstation.",
                "Include a mention of a cracked viewport or stressed panel, suggesting extreme pressure fluctuations.",
                "Describe a datapad on the ground with a single message still visible, as if it was dropped mid-sentence.",
                "Add a faint audio cue from the environment—static-laced alarms, distant hissing, or a looping warning tone.",
                "Include a detail about dust or particulate drifting weightlessly, disturbed only by the player’s movement.",
                "Describe a mismatched set of footprints, some confident and others staggered, telling a silent story.",
                "Add a mention of a shattered container or broken console, its contents scattered like clues across the floor.",
                "Include subtle clues of the crew’s personal lives—a jacket tossed over a chair, a mug labeled with a nickname.",
                "Describe signs of emergency measures abandoned half-executed—sealed doors, unlatched vents, offline modules.",
                "Add a note about scorch marks or chemical burns streaking along a wall, silently outlining the catastrophe.",
                "Include a faint environmental smell or residue—ozone, coolant, burnt insulation—that lingers after the event.",
                "Describe dust settling on powered-down systems, giving the whole area a feeling of forgotten stillness.",
                "Include a note about a diagnostic panel looping the same error code, its display dim but still functioning.",
                "Add a detail about a cargo crate with its mag-seal flickering, barely holding its contents in place.",
                "Mention a handheld scanner left running on low battery, its readout frozen on elevated hazard levels.",
                "Include a micro-detail about ventilation filters clogged with particulate from a ruptured chem batch.",
                "Describe a multi-tool resting beside a panel, still warm from recent use, as if dropped mid-repair.",
                "Add a detail about a coolant line beading with frost, hinting at sudden system depressurization.",
                "Mention a crate marked with outdated corporate branding, suggesting it was never meant to be on the manifest.",
                "Include a faint hum from an auxiliary reactor struggling to maintain minimal power distribution.",
                "Describe an emergency respirator discarded nearby, its indicator light blinking an exhausted amber.",
                "Add a micro-detail about a thermal gauge spiking erratically, a silent record of the system’s failure cascade.",
                "Mention a dataport adapter jammed into an access terminal, showing signs of hurried bypass attempts.",
                "Include a detail about spilled polymer beads rolling across the floor, escaping from a split packing container.",
                "Describe a portable chem stabilizer unit lying on its side, its regulator valves warped from overpressure.",
                "Add a small note about hazard-striping peeling off a bulk container, revealing older warning icons beneath.",
                "Mention a refrigeration crate whose internal fans sputter intermittently, unable to maintain correct temperature.",
                "Include a micro-detail about a fuse array with several slots blown out in a neat, catastrophic sequence.",
                "Describe a handheld atmospheric reader dropped nearby, still chirping intermittent contamination alerts.",
                "Add a detail about fiber-optic bundles hanging loose, their ends glowing faintly under residual charge.",
                "Mention a transport dolly left halfway down a corridor, its inertial locks engaged as if abandoned mid-transfer.",
                "Include a micro-detail about the lingering shimmer of aerosolized chemicals suspended in low gravity."


            };
            Random random = new Random();

            int count = 1 + random.Next(5);

            var selected = PromptOptions
                .OrderBy(x => random.Next())
                .Take(count);

            foreach (var prompt in selected)
            {
                BookPrompt += prompt + " ";
            }

            return BookPrompt;
        }
    }
}
