#!/usr/bin/env bash
# Usage: random_cs.sh <directory>
# Outputs one randomly selected .cs file path from the given directory tree,
# excluding obj/, bin/, and auto-generated files.

dir="${1:-.}"

mapfile -t files < <(
  find "$dir" -name "*.cs" \
    -not -path "*/obj/*" \
    -not -path "*/bin/*" \
    | xargs grep -rL "<auto-generated>" 2>/dev/null \
    | sort
)

count=${#files[@]}

if [ "$count" -eq 0 ]; then
  echo "No .cs files found in $dir" >&2
  exit 1
fi

echo "${files[$((RANDOM % count))]}"
