using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml.Linq;

namespace Retrograde.Story
{
    /// <summary>
    /// The ONLY specific details the AI may reference when generating content
    /// for a beat. Anything not in this object is off-limits.
    ///
    /// Generated by the Fact Planning Pass (one set per beat, frozen before
    /// content generation begins). Parsed from XML output.
    /// </summary>
    public class BeatFacts
    {
        /// <summary>Location name exactly as it should appear in output.</summary>
        public string Location = "";

        /// <summary>
        /// NPCs the AI may reference, by ROLE only (no names).
        /// E.g., "nervous food vendor", "UC security officer"
        /// </summary>
        public List<string> AllowedNpcRoles = new();

        /// <summary>
        /// Objects the AI may reference.
        /// E.g., "encrypted data-slate", "cargo manifest"
        /// </summary>
        public List<string> AllowedObjects = new();

        /// <summary>
        /// Setting details the AI may use for atmosphere.
        /// E.g., "crowded market stalls", "dim service corridor"
        /// </summary>
        public List<string> SettingDetails = new();

        /// <summary>
        /// What the player learns at this beat — the clue or revelation.
        /// Stated as a fact, not a mystery.
        /// </summary>
        public string ClueLearned = "";

        /// <summary>Emotional tone for this beat. E.g., "tense, guarded"</summary>
        public string Tone = "";

        /// <summary>
        /// Bridge text pointing the player to the next location.
        /// Generated separately with minimal context (location pair only),
        /// then injected here before beat content generation.
        /// Empty for the final beat (showdown).
        /// </summary>
        public string BridgeText = "";

        /// <summary>
        /// The beat ID from the schema (e.g., "discovery", "investigation", "showdown").
        /// </summary>
        public string BeatId = "";

        /// <summary>
        /// Build the "ALLOWED VOCABULARY" block for an isolated prompt.
        /// This is the core mechanism: the AI can ONLY use these specifics.
        /// </summary>
        public string BuildVocabularyBlock(string targetName)
        {
            var sb = new StringBuilder();
            sb.AppendLine("ALLOWED VOCABULARY — use ONLY these specifics:");
            sb.AppendLine($"- Location: {Location}");

            if (AllowedNpcRoles.Count > 0)
                sb.AppendLine($"- NPCs (by role only, no names): {string.Join("; ", AllowedNpcRoles)}");

            if (AllowedObjects.Count > 0)
                sb.AppendLine($"- Objects: {string.Join("; ", AllowedObjects)}");

            if (SettingDetails.Count > 0)
                sb.AppendLine($"- Setting: {string.Join("; ", SettingDetails)}");

            if (!string.IsNullOrWhiteSpace(ClueLearned))
                sb.AppendLine($"- Clue: {ClueLearned}");

            if (!string.IsNullOrWhiteSpace(Tone))
                sb.AppendLine($"- Tone: {Tone}");

            if (!string.IsNullOrWhiteSpace(BridgeText))
                sb.AppendLine($"- Lead to next location: {BridgeText}");

            sb.AppendLine();
            sb.AppendLine($"Do not reference any person by name except the target ({targetName}).");
            sb.AppendLine("Do not invent locations, businesses, NPCs, factions, or organizations not listed above.");

            return sb.ToString();
        }

        /// <summary>
        /// Parse a single &lt;BeatFacts&gt; XML element into a BeatFacts instance.
        /// </summary>
        public static BeatFacts ParseXml(XElement element)
        {
            var facts = new BeatFacts();
            facts.BeatId = element.Attribute("beat")?.Value ?? "";
            facts.Location = element.Element("Location")?.Value?.Trim() ?? "";

            var npcRoles = element.Element("NpcRoles")?.Value?.Trim() ?? "";
            if (!string.IsNullOrWhiteSpace(npcRoles))
                facts.AllowedNpcRoles = SplitSemicolon(npcRoles);

            var objects = element.Element("Objects")?.Value?.Trim() ?? "";
            if (!string.IsNullOrWhiteSpace(objects))
                facts.AllowedObjects = SplitSemicolon(objects);

            var setting = element.Element("Setting")?.Value?.Trim() ?? "";
            if (!string.IsNullOrWhiteSpace(setting))
                facts.SettingDetails = SplitSemicolon(setting);

            facts.ClueLearned = element.Element("ClueLearned")?.Value?.Trim() ?? "";
            facts.Tone = element.Element("Tone")?.Value?.Trim() ?? "";

            return facts;
        }

        /// <summary>
        /// Parse all &lt;BeatFacts&gt; elements from an AI response string.
        /// Returns a dictionary keyed by beat ID.
        /// </summary>
        public static Dictionary<string, BeatFacts> ParseAll(string response)
        {
            var result = new Dictionary<string, BeatFacts>();

            // Extract all <BeatFacts ...>...</BeatFacts> blocks
            var pattern = new Regex(@"<BeatFacts[^>]*>.*?</BeatFacts>", RegexOptions.Singleline);
            foreach (Match match in pattern.Matches(response))
            {
                try
                {
                    var element = XElement.Parse(match.Value);
                    var facts = ParseXml(element);
                    if (!string.IsNullOrWhiteSpace(facts.BeatId))
                        result[facts.BeatId] = facts;
                }
                catch
                {
                    // Skip malformed XML blocks
                }
            }

            return result;
        }

        private static List<string> SplitSemicolon(string value)
        {
            var items = new List<string>();
            foreach (var part in value.Split(';'))
            {
                var trimmed = part.Trim();
                if (!string.IsNullOrWhiteSpace(trimmed))
                    items.Add(trimmed);
            }
            return items;
        }
    }
}
