<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Mutagen.Bethesda.Starfield" Version="0.54.0-alpha.89" />
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="Anthropic.SDK" Version="4.1.1" />
    <PackageReference Include="OpenAI" Version="2.6.0" />
    <PackageReference Include="RestSharp" Version="112.1.0" />
    <PackageReference Include="System.Speech" Version="9.0.0" />
  </ItemGroup>

</Project>
